// Familista — AI Decision Engine
// File location: src/services/ai-explainability.service.ts
//
// Wraps a deterministic score with a human-readable rationale. When the LLM
// adapter is configured, the rationale is generated by Claude (and parsed
// strictly). When the LLM is unavailable, a deterministic narrative is built
// directly from the scored factors — every decision is therefore explainable
// regardless of LLM availability.

import { generateNarrative, isLlmConfigured } from './ai-llm.adapter';
import type {
  AIDomain,
  AIDecisionType,
  AISubjectRef,
  DeterministicScore,
  ScoreFactor,
  Alternative,
} from '../types/ai-engine.types';

const WEIGHT_RANK: Record<NonNullable<ScoreFactor['weight']>, number> = {
  CRITICAL: 5,
  HIGH: 4,
  MEDIUM: 3,
  LOW: 2,
  INFO: 1,
};

function rankFactors(factors: ScoreFactor[]): ScoreFactor[] {
  return [...factors].sort((a, b) => {
    const wb = (b.weight ? WEIGHT_RANK[b.weight] : 0) - (a.weight ? WEIGHT_RANK[a.weight] : 0);
    if (wb !== 0) return wb;
    return Math.abs(b.contribution) - Math.abs(a.contribution);
  });
}

function formatValue(v: ScoreFactor['value']): string {
  if (v == null) return 'n/a';
  if (typeof v === 'number') return Math.abs(v) < 100 ? v.toString() : v.toLocaleString();
  if (typeof v === 'boolean') return v ? 'yes' : 'no';
  return String(v);
}

function fallbackNarrative(score: number, urgency: string, top: ScoreFactor[]): string {
  if (top.length === 0) {
    return `Deterministic score ${score.toFixed(1)} (${urgency}). No strong factors detected — recommendation reflects the baseline behaviour for this decision type.`;
  }
  const lines = top
    .slice(0, 4)
    .map((f) => `${f.name} = ${formatValue(f.value)} (${f.contribution >= 0 ? '+' : ''}${f.contribution.toFixed(1)} pts${f.weight ? `, ${f.weight}` : ''})`);
  return `Deterministic score ${score.toFixed(1)} (${urgency}). Drivers: ${lines.join('; ')}.`;
}

export type ExplainabilityResult = {
  rationale: string;
  warnings: string[];
  alternatives: Alternative[];
  confidence: number;
  llm: { used: boolean; tokensIn: number | null; tokensOut: number | null; durationMs: number | null };
};

export type ExplainRequest = {
  domain: AIDomain;
  decisionType: AIDecisionType;
  subject: AISubjectRef;
  deterministic: DeterministicScore;
  features: Record<string, unknown>;
  useLlm?: boolean;
};

export async function explain(req: ExplainRequest): Promise<ExplainabilityResult> {
  const top = rankFactors(req.deterministic.factors);
  const useLlm = req.useLlm !== false && isLlmConfigured();

  if (useLlm) {
    const llm = await generateNarrative({
      domain: req.domain,
      decisionType: req.decisionType,
      subject: req.subject,
      score: req.deterministic.score,
      confidence: req.deterministic.confidence,
      urgency: req.deterministic.urgency,
      features: req.features,
      factors: top,
      recommendation: req.deterministic.recommendation,
      alternatives: req.deterministic.alternatives ?? [],
    });

    if (llm.ok) {
      const finalConfidence = Math.max(0, Math.min(1, req.deterministic.confidence + llm.narrative.confidenceDelta));
      return {
        rationale: llm.narrative.rationale,
        warnings: [...req.deterministic.warnings, ...llm.narrative.warnings],
        alternatives: llm.narrative.alternatives.length > 0
          ? llm.narrative.alternatives
          : (req.deterministic.alternatives ?? []),
        confidence: finalConfidence,
        llm: { used: true, tokensIn: llm.usage.tokensIn, tokensOut: llm.usage.tokensOut, durationMs: llm.usage.durationMs },
      };
    }

    // LLM call failed — degrade gracefully to deterministic narrative
    return {
      rationale: fallbackNarrative(req.deterministic.score, req.deterministic.urgency, top),
      warnings: [...req.deterministic.warnings, `LLM narrative unavailable (${llm.reason}) — deterministic explanation used`],
      alternatives: req.deterministic.alternatives ?? [],
      confidence: req.deterministic.confidence,
      llm: { used: false, tokensIn: llm.usage.tokensIn, tokensOut: llm.usage.tokensOut, durationMs: llm.usage.durationMs },
    };
  }

  return {
    rationale: fallbackNarrative(req.deterministic.score, req.deterministic.urgency, top),
    warnings: req.deterministic.warnings,
    alternatives: req.deterministic.alternatives ?? [],
    confidence: req.deterministic.confidence,
    llm: { used: false, tokensIn: null, tokensOut: null, durationMs: null },
  };
}
