// Familista — Super Admin White-label Control Panel
// File location: src/services/pdf-branding.service.ts
//
// Adapter consumed by the existing Executive PDF Reports (PDFKit) pipeline.
// Returns the resolved branding for a club, including a logo Buffer ready to
// pass to `doc.image(...)`. Cached briefly to avoid re-reading disk per page.

import { prisma } from '../lib/prisma';
import { getActiveAssetBuffer } from './admin-asset.service';
import type { PdfBranding } from '../types/admin.types';

const CACHE_TTL_MS = 60 * 1000;
type CachedBranding = { value: PdfBranding; expiresAt: number };
const cache = new Map<string, CachedBranding>();

function defaultBranding(productName = 'Familista'): PdfBranding {
  return {
    productName,
    tagline: 'Football Intelligence Platform',
    logo: null,
    logoUrl: null,
    colors: {
      primary: '#0f172a',
      secondary: '#64748b',
      accent: '#22c55e',
      text: '#0f172a',
      mutedText: '#64748b',
      border: '#e2e8f0',
      background: '#ffffff',
      surface: '#f8fafc',
    },
    fontFamily: 'Helvetica',
    fontHeadingUrl: null,
    footerText: 'Generated by Familista',
    hidePoweredBy: false,
    supportEmail: null,
    supportUrl: null,
  };
}

function pdfFontFamily(cssFamily: string | null | undefined): string {
  if (!cssFamily) return 'Helvetica';
  const first = cssFamily.split(',')[0]?.trim().replace(/^['"]|['"]$/g, '') ?? '';
  const lower = first.toLowerCase();
  if (lower.includes('times')) return 'Times-Roman';
  if (lower.includes('courier') || lower === 'mono') return 'Courier';
  return 'Helvetica';
}

export async function getPdfBranding(clubId: string): Promise<PdfBranding> {
  const cached = cache.get(clubId);
  if (cached && cached.expiresAt > Date.now()) return cached.value;

  const cfg = await prisma.whiteLabelConfig.findUnique({ where: { clubId } });
  const club = await prisma.club.findUnique({ where: { id: clubId }, select: { name: true } });

  if (!cfg || !cfg.isActive) {
    const branding = defaultBranding(club?.name ?? 'Familista');
    cache.set(clubId, { value: branding, expiresAt: Date.now() + CACHE_TTL_MS });
    return branding;
  }

  const pdfLogo = (await getActiveAssetBuffer(clubId, 'PDF_HEADER')) ?? (await getActiveAssetBuffer(clubId, 'LOGO_LIGHT'));

  const branding: PdfBranding = {
    productName: cfg.productName ?? club?.name ?? 'Familista',
    tagline: cfg.tagline,
    logo: pdfLogo,
    logoUrl: cfg.logoUrl,
    colors: {
      primary: cfg.primaryColor,
      secondary: cfg.secondaryColor,
      accent: cfg.accentColor,
      text: cfg.textColor,
      mutedText: cfg.mutedTextColor,
      border: cfg.borderColor,
      background: cfg.backgroundColor,
      surface: cfg.surfaceColor,
    },
    fontFamily: pdfFontFamily(cfg.fontFamily),
    fontHeadingUrl: cfg.fontHeadingUrl,
    footerText: cfg.hidePoweredBy
      ? cfg.productName ?? club?.name ?? 'Familista'
      : `Generated by ${cfg.productName ?? club?.name ?? 'Familista'} · Powered by Familista`,
    hidePoweredBy: cfg.hidePoweredBy,
    supportEmail: cfg.supportEmail,
    supportUrl: cfg.supportUrl,
  };

  cache.set(clubId, { value: branding, expiresAt: Date.now() + CACHE_TTL_MS });
  return branding;
}

export function invalidatePdfBrandingCache(clubId?: string): void {
  if (clubId) cache.delete(clubId);
  else cache.clear();
}
