/**
 * tests/infrastructure-city.unit.test.ts
 *
 * The Live Infrastructure City — the platform looking at itself.
 *
 * FIVE PROPERTIES, AND THEY ARE THE WHOLE REASON THIS MODULE IS ALLOWED TO
 * CLAIM IT SHOWS AN ARCHITECTURE:
 *
 *   · It INVENTS no component. Every district, building, technology and edge
 *     comes from a manifest generated by reading the repository, and every one
 *     of them carries the file that proves it. There is no hand-written list of
 *     services anywhere — not in the backend, and not in the frontend either.
 *
 *   · It INVENTS no number. There is no request rate, no uptime percentage, no
 *     region, no capacity figure and no package version in this build that the
 *     platform does not actually measure or the lockfile does not actually
 *     state. Where a thing is unmeasured the answer is one of four honest
 *     words, and they mean four different things.
 *
 *   · It LEAKS nothing. The discovery script REFUSES to write a manifest
 *     containing a secret-shaped value — it throws rather than redacting — and
 *     an environment variable reaches the manifest as a NAME or as a count,
 *     never as a value.
 *
 *   · It CHANGES nothing. One write exists on the whole router and it
 *     acknowledges an alert inside this process. No restart, no upgrade, no
 *     deployment, no configuration write.
 *
 *   · It is GUARDED by the platform. The same `assertPlatformOwner` the rest of
 *     SYSTEM uses, applied to the router rather than to the navigation.
 *
 * The frontend half is asserted by reading the source, for the same reason the
 * Data Vault's suite does: these are structural claims — "no second source list
 * exists", "no `EventSource` exists" — and a rendering test would prove them
 * only for the one path it happened to walk.
 */

import fs from 'fs';
import path from 'path';

const ROOT = path.join(__dirname, '..');
const CITY_JS = path.join(ROOT, 'public/infrastructure-city/infrastructure-city.js');
const CITY_CSS = path.join(ROOT, 'public/infrastructure-city/infrastructure-city.css');
const I18N_DIR = path.join(ROOT, 'public/infrastructure-city/i18n');
const APP_JS = path.join(ROOT, 'public/app.js');
const APP_CSS = path.join(ROOT, 'public/app.css');
const INDEX = path.join(ROOT, 'public/index.html');
const DISCOVER = path.join(ROOT, 'scripts/infrastructure-discover.js');
const REGISTRY_TS = path.join(ROOT, 'src/infra/infrastructure-registry.service.ts');
const HEALTH_TS = path.join(ROOT, 'src/infra/infrastructure-health.service.ts');
const ROUTES_TS = path.join(ROOT, 'src/routes/infrastructure.routes.ts');
const MANIFEST = path.join(ROOT, 'src/infra/generated/infrastructure-manifest.json');

const read = (p: string) => fs.readFileSync(p, 'utf8');

/**
 * The file with its comments removed.
 *
 * Several assertions below are of the form "this word never appears". Every one
 * of these files explains at length WHY a connection string can never reach the
 * manifest, so a naive search finds the word in the paragraph promising it is
 * absent. Stripping comments first is the difference between testing the code
 * and testing the prose about the code.
 */
const codeOf = (src: string) => src
  .replace(/\/\*[\s\S]*?\*\//g, ' ')
  .split('\n').map((l) => l.replace(/(^|[^:'"\\])\/\/.*$/, '$1')).join('\n');

// ── the manifest: evidence, not invention ────────────────────────────────────

describe('the manifest is generated from the repository and carries its evidence', () => {
  const manifest = JSON.parse(read(MANIFEST));

  it('exists, and was written by the discovery script rather than by hand', () => {
    expect(manifest.generator).toContain('infrastructure-discover');
    expect(manifest.schemaVersion).toBeGreaterThanOrEqual(1);
    expect(Date.parse(manifest.generatedAt)).not.toBeNaN();
  });

  it('names the files it read, and every one of them exists', () => {
    expect(manifest.evidence.filesRead.length).toBeGreaterThan(4);
    for (const f of manifest.evidence.filesRead) {
      expect(fs.existsSync(path.join(ROOT, f))).toBe(true);
    }
  });

  it('gives every component a file that proves it exists', () => {
    expect(manifest.components.length).toBeGreaterThan(20);
    for (const c of manifest.components) {
      expect(typeof c.sourceEvidence).toBe('string');
      expect(c.sourceEvidence.length).toBeGreaterThan(0);
      expect(c.district).toBeTruthy();
    }
  });

  it('gives every technology a version the lockfile actually states, or null', () => {
    for (const t of manifest.technologies) {
      expect(t.sourceEvidence.length).toBeGreaterThan(0);
      // Never a made-up version: either a real string, or an honest null.
      expect(t.version === null || typeof t.version === 'string').toBe(true);
      if (typeof t.version === 'string') expect(t.version).not.toMatch(/^x|latest|\?/i);
    }
  });

  it('places every component in a district that exists, and every edge between real components', () => {
    const districts = new Set(manifest.districts.map((d: { id: string }) => d.id));
    const components = new Set(manifest.components.map((c: { id: string }) => c.id));
    for (const c of manifest.components) expect(districts.has(c.district)).toBe(true);
    for (const e of manifest.relationships) {
      expect(components.has(e.from)).toBe(true);
      expect(components.has(e.to)).toBe(true);
      expect(e.evidence.length).toBeGreaterThan(0);
    }
    // A future zone is still placed in a real district — it is a plot of land,
    // not a building, and the city draws it as one.
    for (const f of manifest.future) expect(districts.has(f.district)).toBe(true);
  });

  it('carries environment variable NAMES and a count, never a value', () => {
    expect(Array.isArray(manifest.environment.architectural)).toBe(true);
    expect(typeof manifest.environment.secretShapedCount).toBe('number');
    // The shape of the object is the guarantee: there is nowhere for a value
    // to live. A `values`, `env` or `config` map would be the bug.
    expect(Object.keys(manifest.environment).sort()).toEqual(['architectural', 'secretShapedCount', 'total']);
    // And nothing secret-shaped is listed by name either.
    for (const name of manifest.environment.architectural) {
      expect(name).not.toMatch(/SECRET|PASSWORD|TOKEN|KEY|CREDENTIAL|PRIVATE/i);
    }
  });

  it('contains no secret-shaped value anywhere in the file', () => {
    // The same shapes the generator refuses to write, applied to what it wrote.
    const raw = read(MANIFEST);
    const shapes = [
      /postgres(?:ql)?:\/\/[^\s"']+/i, /redis(?:s)?:\/\/[^\s"']+/i, /mongodb(?:\+srv)?:\/\/[^\s"']+/i,
      /\bsk-[A-Za-z0-9_-]{16,}/, /\bsk_live_[A-Za-z0-9]{8,}/, /\brk_live_[A-Za-z0-9]{8,}/,
      /\bAKIA[0-9A-Z]{16}\b/, /\bghp_[A-Za-z0-9]{20,}/, /\bgithub_pat_[A-Za-z0-9_]{20,}/,
      /-----BEGIN [A-Z ]*PRIVATE KEY-----/, /\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\./,
    ];
    for (const re of shapes) expect(raw).not.toMatch(re);
  });

  it('says that a Render deployment is not observable, rather than reporting a region it guessed', () => {
    expect(manifest.deployment.observable).toBe(false);
    expect(manifest.deployment.observabilityNote.length).toBeGreaterThan(20);
    // render.yaml may state a region; anything it does not state stays null.
    for (const s of manifest.deployment.services) {
      expect(s.region === null || typeof s.region === 'string').toBe(true);
    }
  });

  it('reports the database from the Prisma schema rather than from a connection string', () => {
    expect(manifest.database.provider).toBe('postgresql');
    expect(manifest.database.models).toBeGreaterThan(0);
    expect(manifest.database.migrations).toBeGreaterThanOrEqual(0);
  });
});

describe('the discovery script refuses to write a secret rather than redacting one', () => {
  const src = codeOf(read(DISCOVER));

  it('throws on a secret-shaped value instead of masking it', () => {
    expect(src).toContain('function assertNoSecrets');
    const fn = src.slice(src.indexOf('function assertNoSecrets'), src.indexOf('function assertNoSecrets') + 900);
    expect(fn).toMatch(/throw new Error/);
    // A redaction would mean the value was in the object in the first place,
    // and the next shape nobody thought of would ship.
    expect(fn).not.toMatch(/\breplace\s*\(/);
  });

  it('never reads a runtime environment value at all', () => {
    // Stronger than filtering values out: the script does not read the process
    // environment. It reads the variable NAMES declared in render.yaml, so a
    // value has no path into the process, let alone into the manifest.
    expect(src).not.toMatch(/process\.env/);
    // The capture group is the key. Extending it to the value is the one edit
    // that would break this guarantee, and it would have to break this line.
    expect(src).toContain('/^\\s*-\\s*key:\\s*([A-Z0-9_]+)\\s*$/gm');
    expect(src).toContain('secretShapedCount');
  });

  it('can verify its own output is current without rewriting it', () => {
    expect(src).toContain('--check');
    // Staleness must ignore the timestamp, or every check fails on a clean tree.
    expect(src).toMatch(/generatedAt/);
  });

  it('is run by the build, so the manifest cannot be stale in a deployed server', () => {
    const pkg = JSON.parse(read(path.join(ROOT, 'package.json')));
    expect(pkg.scripts['infra:discover']).toContain('infrastructure-discover');
    expect(pkg.scripts.build).toContain('infra');
    // And it is copied beside the compiled module, or the server cannot read it.
    expect(read(path.join(ROOT, 'scripts/copy-runtime-assets.js'))).toContain('infra');
  });
});

// ── the registry ─────────────────────────────────────────────────────────────

describe('the technology registry', () => {
  const src = codeOf(read(REGISTRY_TS));

  it('reports a missing manifest as a named state with the command that fixes it', () => {
    expect(src).toContain("state: 'NOT_GENERATED'");
    expect(src).toContain("remedy: 'npm run infra:discover'");
  });

  it('computes the inverse of a dependency rather than storing a second copy', () => {
    const fn = src.slice(src.indexOf('export function dependentsOf'), src.indexOf('export function dependenciesOf'));
    expect(fn).toContain('c.dependencies.includes(id)');
    expect(fn).not.toMatch(/dependents\s*:/);
  });

  it('holds no absolute coordinate, so a new component needs no redraw', () => {
    const layout = src.slice(src.indexOf('export function cityLayout'));
    expect(layout).not.toMatch(/\b(x|y|left|top|cx|cy)\s*:/);
    expect(layout).toContain('zone');
    expect(layout).toContain('priority');
  });

  it('caches the manifest, because an inventory cannot change while the process runs', () => {
    expect(src).toContain('if (cached) return cached;');
    expect(src).toContain('export function resetInfrastructureRegistry');
  });
});

// ── rules, incidents and transitions ─────────────────────────────────────────

const published: { service: string; from: string; to: string; latencyMs: number | null }[] = [];

jest.mock('../src/config/database', () => ({
  prisma: { $queryRaw: async () => [{ '?column?': 1 }] },
}));
jest.mock('../src/fabric/producers/system.producer', () => ({
  publishSystemHealthChanged: (service: string, from: string, to: string, latencyMs: number | null) => {
    published.push({ service, from, to, latencyMs });
  },
}));

// eslint-disable-next-line @typescript-eslint/no-var-requires
const health = require('../src/infra/infrastructure-health.service');

type S = { key: string; state: string; summary: string; measurements: Record<string, unknown>; evidence: string; measuredAt: string };
const signal = (key: string, state: string, measurements: Record<string, unknown> = {}): S => ({
  key, state, summary: '', measurements, evidence: 'test', measuredAt: new Date().toISOString(),
});

describe('incidents come from named rules with stated thresholds', () => {
  beforeEach(() => { published.length = 0; health.resetInfrastructureIncidents(); });

  it('gives every rule a threshold a person can read, and a next step it does not perform itself', () => {
    expect(health.INFRASTRUCTURE_RULES.length).toBeGreaterThanOrEqual(10);
    for (const r of health.INFRASTRUCTURE_RULES) {
      expect(r.condition.length).toBeGreaterThan(10);
      expect(r.nextStep.length).toBeGreaterThan(10);
      expect(r.impact.length).toBeGreaterThan(10);
      expect(['CRITICAL', 'WARNING', 'INFO']).toContain(r.severity);
      expect(r.componentId).toBeTruthy();
      expect(r.districtId).toBeTruthy();
    }
    const ids = health.INFRASTRUCTURE_RULES.map((r: { id: string }) => r.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('names every threshold in one place, and lets the deployment override it', () => {
    const src = codeOf(read(HEALTH_TS));
    const block = src.slice(src.indexOf('export const THRESHOLDS'), src.indexOf('} as const;'));
    // Every threshold reads an env var: a number buried in an `if` is a number
    // nobody can question and nobody can tune.
    const entries = [...block.matchAll(/(\w+):\s*Number\(process\.env\.(\w+)/g)];
    expect(entries.length).toBeGreaterThanOrEqual(10);
    expect(Object.keys(health.THRESHOLDS).sort()).toEqual(entries.map((m) => m[1]).sort());
  });

  it('opens an incident when a rule starts firing', () => {
    const out = health.evaluate([signal('database', 'WARNING', { latencyMs: 400, warnMs: 250, criticalMs: 1000 })]);
    const inc = out.find((i: { ruleId: string }) => i.ruleId === 'db-latency');
    expect(inc).toBeTruthy();
    expect(inc.status).toBe('OPEN');
    expect(inc.occurrences).toBe(1);
    expect(inc.evidence.latencyMs).toBe(400);
    expect(inc.severity).toBe('WARNING');
  });

  it('deduplicates: the same rule still firing is the same incident, not news', () => {
    const first = health.evaluate([signal('database', 'WARNING', { latencyMs: 400, warnMs: 250 })]);
    const id = first.find((i: { ruleId: string }) => i.ruleId === 'db-latency').id;
    health.evaluate([signal('database', 'WARNING', { latencyMs: 410, warnMs: 250 })]);
    const again = health.evaluate([signal('database', 'WARNING', { latencyMs: 420, warnMs: 250 })]);
    const inc = again.find((i: { ruleId: string }) => i.ruleId === 'db-latency');
    expect(inc.id).toBe(id);
    expect(inc.occurrences).toBe(3);
    expect(inc.evidence.latencyMs).toBe(420);
    expect(again.filter((i: { ruleId: string }) => i.ruleId === 'db-latency')).toHaveLength(1);
  });

  it('resolves an incident when the rule stops firing, and keeps it', () => {
    health.evaluate([signal('database', 'WARNING', { latencyMs: 400, warnMs: 250 })]);
    health.evaluate([signal('database', 'HEALTHY', { latencyMs: 8, warnMs: 250 })]);
    expect(health.openIncidents().filter((i: { ruleId: string }) => i.ruleId === 'db-latency')).toHaveLength(0);
    const gone = health.resolvedIncidents().find((i: { ruleId: string }) => i.ruleId === 'db-latency');
    expect(gone.status).toBe('RESOLVED');
    expect(gone.resolvedAt).toBeTruthy();
  });

  it('distinguishes an unreachable database from a slow one', () => {
    // CRITICAL with no threshold in the evidence is a failed probe; CRITICAL
    // with thresholds is a round trip that took too long. Two different
    // problems, two different rules, two different next steps.
    const down = health.evaluate([signal('database', 'CRITICAL', { latencyMs: 30 })]);
    expect(down.map((i: { ruleId: string }) => i.ruleId)).toContain('db-unreachable');
    expect(down.map((i: { ruleId: string }) => i.ruleId)).not.toContain('db-latency');

    health.resetInfrastructureIncidents();
    const slow = health.evaluate([signal('database', 'CRITICAL', { latencyMs: 4000, warnMs: 250, criticalMs: 1000 })]);
    expect(slow.map((i: { ruleId: string }) => i.ruleId)).toContain('db-latency');
    expect(slow.map((i: { ruleId: string }) => i.ruleId)).not.toContain('db-unreachable');
  });

  it('orders incidents by severity, so the worst thing is the first thing', () => {
    const out = health.evaluate([
      signal('objectStore', 'NOT_CONFIGURED'),
      signal('database', 'WARNING', { latencyMs: 400, warnMs: 250 }),
      signal('redis', 'CRITICAL', { configured: true, connected: false }),
    ]);
    expect(out.map((i: { severity: string }) => i.severity)).toEqual(['CRITICAL', 'WARNING', 'INFO']);
  });

  it('acknowledges an incident in this process, and says that is the scope', () => {
    const [inc] = health.evaluate([signal('redis', 'CRITICAL', {})]);
    const ack = health.acknowledgeIncident(inc.id);
    expect(ack.status).toBe('ACKNOWLEDGED');
    expect(ack.acknowledgedAt).toBeTruthy();
    expect(health.acknowledgeIncident('inc_nothing')).toBeNull();
    // And the limitation is stated in the type, not only in a comment.
    expect(codeOf(read(HEALTH_TS))).toContain("scope: 'PROCESS'");
    expect(codeOf(read(ROUTES_TS))).toContain("scope: 'PROCESS'");
  });

  it('creates no database table to hold any of this', () => {
    // §42: a migration for visualisation is not made without saying why first.
    // Incidents derive from live evidence; their transitions ride the Fabric
    // into the Historical Event Store, which already exists.
    const src = codeOf(read(HEALTH_TS));
    expect(src).not.toMatch(/prisma\.\w*[Ii]ncident/);
    expect(src).toContain('const open = new Map<string, Incident>()');
    const schema = read(path.join(ROOT, 'prisma/schema.prisma'));
    expect(schema).not.toMatch(/model\s+Infra\w*/);
    expect(schema).not.toMatch(/model\s+\w*Incident\b/);
  });
});

describe('the Data Fabric hears about transitions, never about heartbeats', () => {
  beforeEach(() => { published.length = 0; health.resetInfrastructureIncidents(); });

  it('publishes nothing on the first observation of a signal', () => {
    health.evaluate([signal('database', 'HEALTHY', { latencyMs: 5 })]);
    expect(published).toEqual([]);
  });

  it('publishes nothing while a state is unchanged, however many times it is polled', () => {
    for (let i = 0; i < 25; i += 1) health.evaluate([signal('database', 'HEALTHY', { latencyMs: 5 })]);
    expect(published).toEqual([]);
  });

  it('publishes exactly once when the state actually changes', () => {
    health.evaluate([signal('database', 'HEALTHY', { latencyMs: 5 })]);
    health.evaluate([signal('database', 'WARNING', { latencyMs: 400, warnMs: 250 })]);
    health.evaluate([signal('database', 'WARNING', { latencyMs: 420, warnMs: 250 })]);
    expect(published).toHaveLength(1);
    expect(published[0]).toMatchObject({ service: 'infrastructure:database', from: 'HEALTHY', to: 'WARNING' });
    expect(published[0].latencyMs).toBe(400);
  });

  it('never publishes a signal that cannot change', () => {
    // NOT_INSTRUMENTED and UNVERIFIED are statements about this build, not
    // observations of a system. A "transition" between them is meaningless and
    // would fill the historical store with it.
    health.evaluate([signal('ci', 'NOT_INSTRUMENTED'), signal('deployment', 'UNVERIFIED')]);
    health.evaluate([signal('ci', 'NOT_INSTRUMENTED'), signal('deployment', 'UNVERIFIED')]);
    expect(published).toEqual([]);
  });

  it('cannot break the publisher it is observing', () => {
    const src = codeOf(read(HEALTH_TS));
    const fn = src.slice(src.indexOf('function publishTransitions'), src.indexOf('export function openIncidents'));
    expect(fn).toContain('try {');
    expect(fn).toMatch(/catch\s*\(/);
    expect(fn).toContain('logger.warn');
  });

  it('registers no new event type — it reuses the contract that already exists', () => {
    const src = codeOf(read(HEALTH_TS));
    expect(src).toContain('publishSystemHealthChanged');
    expect(src).not.toMatch(/registerEvent|defineEvent|EVENT_TYPES\s*\./);
    const registry = read(path.join(ROOT, 'src/fabric/registry/event-registry.ts'));
    expect(registry).not.toMatch(/infrastructure\./);
  });
});

describe('a signal nothing measures says so rather than showing green', () => {
  it('has four different words for four different reasons', () => {
    const src = read(HEALTH_TS);
    for (const w of ['NOT_INSTRUMENTED', 'NOT_CONFIGURED', 'UNVERIFIED', 'UNKNOWN']) {
      expect(src).toContain(w);
    }
    expect(codeOf(src)).toContain("export type HealthState = 'HEALTHY' | 'WARNING' | 'CRITICAL' | 'NOT_CONFIGURED' | 'NOT_INSTRUMENTED' | 'UNVERIFIED' | 'UNKNOWN'");
  });

  it('reports CI and test health as uninstrumented rather than reading a green tick as health', () => {
    const src = codeOf(read(HEALTH_TS));
    const ci = src.slice(src.indexOf('function ciSignal'), src.indexOf('function testsSignal'));
    expect(ci).toContain("state: 'NOT_INSTRUMENTED'");
    const tests = src.slice(src.indexOf('function testsSignal'), src.indexOf('function aiSignal'));
    expect(tests).toContain("state: 'NOT_INSTRUMENTED'");
  });

  it('reports deployment as UNVERIFIED, because this process genuinely cannot see it', () => {
    const src = codeOf(read(HEALTH_TS));
    const dep = src.slice(src.indexOf('function deploymentSignal'), src.indexOf('function ciSignal'));
    expect(dep).toContain("state: 'UNVERIFIED'");
    expect(dep).not.toMatch(/HEALTHY/);
  });

  it('measures the database with a real round trip rather than the existence of a pool', () => {
    const src = codeOf(read(HEALTH_TS));
    expect(src).toContain('prisma.$queryRaw`SELECT 1`');
  });

  it('invents no rate, uptime, region or capacity figure', () => {
    const src = codeOf(read(HEALTH_TS)) + codeOf(read(ROUTES_TS)) + codeOf(read(CITY_JS));
    // The words that would signal a fabricated metric. `uptime` is allowed in
    // the process signal only, where it is `process.uptime()` — a real reading.
    expect(src).not.toMatch(/requestsPerSecond|rps\b|qps\b|throughputPerMin/i);
    expect(src).not.toMatch(/uptimePercent|availabilityPercent|slaPercent/i);
    expect(src).not.toMatch(/Math\.random/);
    for (const m of src.matchAll(/uptime\w*/gi)) {
      expect(['uptime', 'uptimeSeconds', 'uptimeSec']).toContain(m[0]);
    }
  });
});

// ── the API ──────────────────────────────────────────────────────────────────

describe('the Infrastructure API is the platform owner\'s, and it is read-only', () => {
  const src = codeOf(read(ROUTES_TS));

  it('is guarded by the platform rather than by the navigation', () => {
    expect(src).toContain('router.use(authenticate);');
    expect(src).toContain('assertPlatformOwner');
    // The guard is on the ROUTER, above every route, so a route added tomorrow
    // inherits it rather than having to remember it.
    expect(src.indexOf('assertPlatformOwner')).toBeLessThan(src.indexOf("router.get('/'"));
  });

  it('is mounted under SYSTEM, once', () => {
    const index = read(path.join(ROOT, 'src/routes/index.ts'));
    expect(index).toContain("router.use('/system/infrastructure', infrastructureRoutes)");
    expect((index.match(/infrastructureRoutes/g) || [])).toHaveLength(2);   // import + mount
  });

  it('has exactly one write, and it changes nothing outside this process', () => {
    const writes = [...src.matchAll(/router\.(post|put|patch|delete)\(/g)].map((m) => m[1]);
    expect(writes).toEqual(['post']);
    expect(src).toContain("router.post('/incidents/:id/acknowledge'");
    // Nothing here restarts, deploys, upgrades or writes configuration. Asserted
    // on the MECHANISMS rather than the words: "restart" appears legitimately in
    // the sentence explaining that acknowledgement does not survive one.
    expect(src).not.toMatch(/child_process|execSync|execFile|\bspawn\(|\bexec\(/);
    expect(src).not.toMatch(/\bfetch\(|axios|got\(|https?\.request/);
    expect(src).not.toMatch(/prisma\.\w+\.(create|update|delete|upsert|createMany|updateMany|deleteMany)/);
  });

  it('returns no environment value, connection string or token', () => {
    expect(src).not.toMatch(/process\.env\.(?!INFRA_STREAM_MS)/);
    expect(src).not.toMatch(/DATABASE_URL|REDIS_URL|ANTHROPIC_API_KEY|JWT_SECRET/);
  });

  it('paces its own stream, so a fast client cannot hammer a struggling platform', () => {
    const stream = src.slice(src.indexOf("router.get('/stream'"));
    expect(stream).toContain('INFRA_STREAM_MS');
    expect(stream).toMatch(/Math\.min\(Math\.max\([\s\S]*?,\s*5_000\)\s*,\s*60_000\)/);
    expect(stream).toContain("res.setHeader('Content-Type', 'text/event-stream')");
    expect(stream).toContain("res.setHeader('X-Accel-Buffering', 'no')");
    // A client that walks away must not leave a timer running for ever.
    expect(stream).toContain("req.on('close', close)");
    expect(stream).toContain('clearInterval(timer)');
    expect(stream).toContain('timer.unref');
  });

  it('sends the roads with the buildings, so the city can draw its connections', () => {
    // The regression this pins, found in a rendered screenshot rather than by a
    // test: the inventory sent districts, components and future plots but NOT
    // relationships. The frontend guards each read with `|| []`, so nothing
    // threw — the Connections list, the Change Impact paths and the dependency
    // highlight an alert lights up simply rendered empty. Failing loudly would
    // have been better; sending the data is better still.
    const inventory = src.slice(src.indexOf("router.get('/'"), src.indexOf("router.get('/health'"));
    for (const field of ['districts', 'components', 'relationships', 'future', 'layout']) {
      expect(inventory).toMatch(new RegExp(`\\b${field}:`));
    }
    // And every place the frontend reads them is fed by that one response.
    const city = codeOf(read(CITY_JS));
    expect(city).toContain('IC.manifest.relationships');
    expect(city.match(/IC\.manifest\.relationships/g)!.length).toBeGreaterThanOrEqual(2);
  });

  it('answers a missing manifest with one shape, on every route that needs it', () => {
    expect(src).toContain('function notGenerated');
    expect((src.match(/notGenerated\(res/g) || []).length).toBeGreaterThanOrEqual(3);
  });

  it('reads change history from the store that already holds it', () => {
    const changes = src.slice(src.indexOf("router.get('/changes'"), src.indexOf("router.get('/components/:id'"));
    expect(changes).toContain('queryHistory');
    expect(changes).toContain("source: 'Historical Event Store'");
    // A CI tick is not a deployment, and the endpoint says so in its payload.
    expect(changes).toContain("state: 'UNVERIFIED'");
  });

  it('states that no vulnerability scanner runs, rather than implying a clean bill', () => {
    const tech = src.slice(src.indexOf("router.get('/technology'"), src.indexOf("router.get('/changes'"));
    expect(tech).toContain('vulnerabilityScanning');
    expect(tech).toContain("state: 'NOT_INSTRUMENTED'");
  });
});

// ── the interface ────────────────────────────────────────────────────────────

describe('the Infrastructure City interface', () => {
  const src = read(CITY_JS);
  const code = codeOf(src);
  const css = read(CITY_CSS);

  it('holds no hand-written list of services, technologies or versions', () => {
    // The whole point: the city renders the manifest. A literal list here would
    // be a second source of truth, and the two would drift within a month.
    expect(code).not.toMatch(/['"]PostgreSQL['"]\s*,\s*['"]Redis['"]/);
    expect(code).not.toMatch(/version:\s*['"]\d+\.\d+/);
    expect(code).toContain('IC.manifest');
  });

  it('reads the live stream with fetch rather than the browser event-source object', () => {
    // `data-pulse.js` states the reason: that object cannot set headers, so it
    // would force the access token into a query string where every proxy in the
    // path writes it to a log.
    expect(code).not.toContain('EventSource');
    expect(code).toContain('res.body.getReader()');
    expect(code).toContain("Authorization: 'Bearer ' + t");
  });

  it('never puts a token in a URL', () => {
    expect(code).not.toMatch(/[?&](token|access_token|jwt|auth)=/);
    expect(code).not.toMatch(/\+\s*token\(\)/);
  });

  it('falls back to a bounded poll rather than reconnecting for ever', () => {
    const fn = code.slice(code.indexOf('function startStream'), code.indexOf('function onHealthFrame'));
    expect(fn).toContain('IC.stream.attempts >= 4');
    expect(fn).toContain('startPolling');
    expect(fn).toMatch(/Math\.min\(retryAt \* 2, 20000\)/);
    // And it says on screen that it is degraded: a silent reconnect makes a
    // dead stream look like an idle platform.
    expect(fn).toContain("IC.stream.state = 'CONNECTING'");
    expect(code).toContain("IC.stream.state = 'POLLING'");
  });

  it('maps every health state to a colour in exactly one place', () => {
    const fn = code.slice(code.indexOf('function stateKind'), code.indexOf('function stateLabel'));
    for (const s of ['HEALTHY', 'WARNING', 'CRITICAL', 'NOT_CONFIGURED', 'NOT_INSTRUMENTED', 'UNVERIFIED', 'FUTURE']) {
      expect(fn).toContain(`case '${s}'`);
    }
    // Nothing else may decide a colour from a state string.
    expect((code.match(/case 'HEALTHY'/g) || [])).toHaveLength(2);   // stateKind + stateLabel
  });

  it('offers four views over one state, rather than four screens', () => {
    expect(code).toContain("[['city', 'City View'], ['map', 'Map View'], ['topology', 'Topology'], ['table', 'Table']]");
    // One state object feeds all four: switching a view must not refetch.
    const bind = code.slice(code.indexOf('var view = t.closest(\'[data-ic-view]\')'), code.indexOf('var view = t.closest(\'[data-ic-view]\')') + 400);
    expect(bind).not.toMatch(/load\w+\(|fetch\(/);
  });

  it('numbers its dependency layers consecutively, and stops relaxing when it converges', () => {
    // Two regressions, both found in a rendered screenshot. The relaxation ran a
    // fixed six passes — too few once the real relationships arrived — and the
    // RAW depth was printed, so the reader saw "Layer 0, Layer 1, Layer 2,
    // Layer 11": an implementation detail of the relaxation, not the shape of
    // the graph. Order is what carries the meaning, so the depths are ranked.
    const fn = code.slice(code.indexOf('var depth = {};'), code.indexOf('var list ='));
    expect(fn).toContain('if (!moved) break;');
    expect(fn).toMatch(/Math\.min\(comps\.length \+ 1, 64\)/);   // and it terminates on a cycle
    expect(fn).toContain('var rank = {};');
    expect(fn).toContain('distinct.forEach(function (d, i) { rank[d] = i; });');
    expect(fn).toContain('var k = rank[depth[c.id] || 0];');
    expect(fn).not.toMatch(/var k = depth\[c\.id\]/);
  });

  it('takes the reader from an alert to the place it happened', () => {
    const fn = code.slice(code.indexOf('function locate(host, incidentId)'), code.indexOf('function bind(host)'));
    expect(fn).toContain('IC.focusDistrict = inc.districtId');
    expect(fn).toContain('IC.focusComponent = inc.componentId');
    expect(fn).toContain('IC.focusPaths');
    expect(fn).toContain('IC.inspect = inc.componentId');
    expect(fn).toContain('scrollIntoView');
  });

  it('moves nothing the reader did not move', () => {
    // The rule the whole design system is built on. A floating surface is
    // fixed and animates on opacity and transform only; the workspace body
    // scrolls inside itself with a stable gutter.
    expect(css).toMatch(/\.ic-insp\s*\{[^}]*position:\s*fixed/);
    expect(css).toMatch(/\.ic-insp-scrim\s*\{[^}]*position:\s*fixed/);
    expect(css).toContain('scrollbar-gutter: stable');
    const keyframes = [...css.matchAll(/@keyframes ic-[\w-]+ \{([^}]*\{[^}]*\}[^}]*)*\}/g)].map((m) => m[0]).join('');
    expect(keyframes).not.toMatch(/(^|[^-])(width|height|margin|padding|top|left):/);
    // And a health frame repaints the one region that changed.
    expect(code).toContain('function repaintBody');
    const frame = code.slice(code.indexOf('function onHealthFrame'), code.indexOf('function locate('));
    expect(frame).toContain('repaintBody(host)');
    expect(frame).toContain('refreshChrome(host)');
  });

  it('renders a measured zero as a zero and an unmeasured figure as a dash', () => {
    expect(code).toMatch(/function (fig|num|dash)/);
    expect(code).toContain("'—'");
    // A placeholder number is the one thing that must never appear.
    expect(code).not.toMatch(/\|\|\s*(99|100|42|0\.99)\b/);
  });

  it('gives every section an empty state that names what is missing', () => {
    expect(code).toContain('function emptyState');
    expect((code.match(/emptyState\(/g) || []).length).toBeGreaterThan(5);
    expect(code).toContain('NOT_GENERATED');
    // The remedy is a command, so it is marked as an identifier rather than
    // translated — translating `npm run infra:discover` would break it.
    expect(code).toContain('<code data-no-i18n>npm run infra:discover</code>');
  });

  it('stays on one screen', () => {
    // No navigation away and back: the inspector is a panel, the views are
    // internal, and the only exit is the deliberate one to the owner home.
    expect((code.match(/window\.navTo\(/g) || [])).toHaveLength(1);
    expect(code).toContain("window.navTo('owner-home')");
  });

  it('returns to normal scrolling rather than crushing panels on a small screen', () => {
    expect(css).toContain('@media (max-width: 980px), (max-height: 620px)');
    for (const w of [1660, 1400, 1280, 1100]) expect(css).toContain(`max-width: ${w}px`);
  });

  it('keeps the top bar above the panels it floats over', () => {
    // The Data Vault's lesson, paid for once: a `backdrop-filter` creates a
    // stacking context, so a menu in a bar without its own z-index renders
    // behind the content and cannot be clicked.
    expect(css).toMatch(/\.ic-top\s*\{[^}]*position:\s*relative[^}]*z-index:\s*40/);
  });

  it('escapes everything it renders', () => {
    expect(code).toContain('function esc(');
    // Every interpolation of a manifest or health value goes through it.
    expect(code).not.toMatch(/innerHTML\s*=\s*[^;]*\+\s*(c|d|t|s)\.(name|id|summary)\b/);
  });
});

// ── localisation ─────────────────────────────────────────────────────────────

describe('the Infrastructure City speaks English, German and Arabic — and only those', () => {
  const en = JSON.parse(read(path.join(I18N_DIR, 'en.json')));
  const de = JSON.parse(read(path.join(I18N_DIR, 'de.json')));
  const ar = JSON.parse(read(path.join(I18N_DIR, 'ar.json')));
  const src = read(CITY_JS);
  const code = codeOf(src);

  it('ships exactly three catalogues', () => {
    expect(fs.readdirSync(I18N_DIR).sort()).toEqual(['ar.json', 'de.json', 'en.json']);
  });

  it('declares the three locales and their directions', () => {
    expect(code).toContain("[['en', 'English', 'ltr'], ['de', 'Deutsch', 'ltr'], ['ar', 'العربية', 'rtl']]");
  });

  it('has a German and an Arabic entry for every English key', () => {
    const keys = Object.keys(en);
    expect(keys.length).toBeGreaterThan(120);
    expect(Object.keys(de).sort()).toEqual([...keys].sort());
    expect(Object.keys(ar).sort()).toEqual([...keys].sort());
  });

  it('actually translates — nothing is left in English', () => {
    // The words that are the same in every language: product names, technical
    // identifiers and the four state words the platform uses as tokens.
    const sameEverywhere = new Set(['Familista', 'Data Fabric', 'Data Vault', 'PostgreSQL', 'Redis',
      'Prisma', 'Node.js', 'TypeScript', 'Express', 'Render', 'CI', 'API', 'SSE', 'Status', 'Format']);
    const leftInEnglish = Object.entries(ar).filter(([k, v]) => !sameEverywhere.has(k) && v === k);
    expect(leftInEnglish).toEqual([]);
    for (const [k, v] of Object.entries(de)) {
      expect(typeof v).toBe('string');
      expect((v as string).length).toBeGreaterThan(0);
      void k;
    }
  });

  it('writes Arabic in Arabic script', () => {
    expect(ar['Infrastructure City']).toMatch(/[\u0600-\u06FF]/);
    expect(ar['Alerts & Incidents']).toMatch(/[\u0600-\u06FF]/);
    expect(ar['Technology Map']).toMatch(/[\u0600-\u06FF]/);
    expect(ar['Not instrumented']).toMatch(/[\u0600-\u06FF]/);
  });

  it('sets the document direction from the locale, so Arabic renders RTL', () => {
    expect(code).toContain("host.setAttribute('dir', IC_DIR)");
    expect(code).toContain('IC_DIR = l[2]');
  });

  it('lays the shell out for RTL rather than only flipping the text', () => {
    const css = read(CITY_CSS);
    expect(css).toContain('#pg-infrastructure-city[dir="rtl"] .ic-shell { flex-direction: row-reverse; }');
    expect(css).toContain('border-inline-end');
    expect(css).toContain('inset-inline-end');
    expect(css).toContain('padding-inline-start');
    // The inspector is pinned to the inline end, so in Arabic it sits on the
    // left of the viewport and must enter from the left.
    expect(css).toContain('@keyframes ic-slide-rtl');
    expect(css).toContain('#pg-infrastructure-city[dir="rtl"] .ic-insp { animation-name: ic-slide-rtl; }');
  });

  it('never translates a technology name, a component id or a version', () => {
    expect(code).toMatch(/data-no-i18n/);
    const walker = code.slice(code.indexOf('function icTranslate'), code.indexOf('function languageSwitchHtml'));
    expect(walker).toContain("hasAttribute('data-no-i18n')");
    expect(walker).toContain("hasAttribute('data-user-content')");
  });

  it('keeps its catalogue out of the platform\'s club-facing locale files', () => {
    const app = read(APP_JS);
    expect(app).toContain('<div class="page" id="pg-infrastructure-city" data-no-i18n>');
    const clubCatalogue = JSON.parse(read(path.join(ROOT, 'public/i18n/catalogue/de-DE.json')));
    expect(clubCatalogue['Infrastructure City']).toBeUndefined();
    expect(clubCatalogue['Not instrumented']).toBeUndefined();
  });

  it('is not scanned by the platform extractor, and that is deliberate', () => {
    // If this changes, the module's strings land in 31 club-facing locale files
    // overnight. The boundary is the extractor's explicit source list.
    const extractor = read(path.join(ROOT, 'scripts/i18n-extract.js'));
    const sources = extractor.slice(extractor.indexOf('const SOURCES = ['), extractor.indexOf('const OUT'));
    expect(sources).not.toContain('infrastructure-city');
  });

  it('has a catalogue entry for every string the module asks it to translate', () => {
    const asked = new Set<string>();
    for (const m of code.matchAll(/\bT\(\s*'((?:[^'\\]|\\.)*)'\s*\)/g)) asked.add(m[1].replace(/\\'/g, "'"));
    // And the T(variable) call sites, fed from these lists. A literal-only scan
    // cannot see them, and that is exactly the gap that shipped four English
    // labels inside an Arabic page once before.
    const listOf = (re: RegExp) => (code.match(re) || [''])[0];
    const lists = [
      listOf(/var SECTIONS = \[[\s\S]*?\];/),
      listOf(/var GROUP_LABEL = \{[\s\S]*?\};/),
      listOf(/var views = \[[\s\S]*?\];/),
    ];
    for (const block of lists) {
      expect(block.length).toBeGreaterThan(0);
      for (const m of block.matchAll(/'((?:[^'\\]|\\.)*)'/g)) {
        const v = m[1].replace(/\\'/g, "'");
        if (/^[A-Z]/.test(v) && /[a-z ]/.test(v)) asked.add(v);
      }
    }
    expect(asked.size).toBeGreaterThan(100);
    expect([...asked].filter((k) => !(k in en))).toEqual([]);
  });

  it('translates the manifest\'s descriptions and leaves its technology names alone', () => {
    // The city draws names that come from JSON, not from the source file, so the
    // ratchets above cannot see them. This is the ratchet for those.
    //
    // The mechanism is the catalogue itself: a name with an entry is translated,
    // a name without one falls through `T` unchanged. There is no second list of
    // "do not translate" to keep in step with anything — absence IS the
    // instruction, which is why a technology can never be translated by accident.
    const manifest = JSON.parse(read(MANIFEST));

    // Every district and every component name reaches the reader through T().
    expect(code).toContain('esc(T(d.name))');
    expect(code).toContain('esc(T(c.name))');
    expect(code).toContain('esc(T(f.name))');

    // A description the discovery script composed must be translated, or an
    // Arabic reader gets an Arabic frame around an English diagram.
    for (const name of ['Backend Services', 'Security & Access', 'Storage & Media',
      'Historical Event Store', 'Rate Limiting', 'Object Storage', 'Health Monitoring',
      'Test Suite', 'Languages & Runtime', 'Realtime Transport']) {
      expect(manifest.districts.concat(manifest.components).some((x: { name: string }) => x.name === name)).toBe(true);
      expect(en[name]).toBeDefined();
      expect(ar[name]).toMatch(/[\u0600-\u06FF]/);
      expect(de[name]).toBeTruthy();
    }

    // A technology or product name must NOT be, in any of the three.
    for (const name of ['PostgreSQL', 'Prisma ORM', 'Redis', 'Node.js', 'TypeScript', 'Stripe',
      'Anthropic', 'familista-backend', 'familista-redis', 'familista-postgres',
      'GitHub Actions — ci', 'GitHub Actions — deploy', 'SYSTEM', 'DATA VAULT',
      'Data Fabric', 'Data Vault', 'Familista Platform Core', 'Scouting', 'Snapshots']) {
      expect(en[name]).toBeUndefined();
      expect(de[name]).toBeUndefined();
      expect(ar[name]).toBeUndefined();
    }

    // A package name, a version and an enum token are identifiers wherever they
    // appear, and stay marked as such.
    expect(code).toContain('<span class="ic-td-name" data-no-i18n>\' + esc(d.name)');
    expect(code).toContain('<span class="ic-building-ver" data-no-i18n>');
    expect(code).toContain('<span class="ic-edge-kind" data-no-i18n>');
  });

  it('leaves no prose in the markup that the catalogue has never seen', () => {
    // The strongest of the three ratchets: a string sitting literally between
    // > and < in a markup template IS text the translator walks. If it is not
    // in the catalogue it renders in English, whatever the locale.
    const leaks: string[] = [];
    for (const m of code.matchAll(/'((?:[^'\\\n]|\\.)*)'/g)) {
      const lit = m[1];
      if (!lit.includes('>')) continue;
      for (const t of lit.matchAll(/(<[^<>]*>)([^<>]{3,})</g)) {
        const tag = t[1];
        const text = t[2].replace(/\\'/g, "'").trim();
        if (!text || !/[a-z]{3}/.test(text)) continue;
        if (/^[\s\d.,:%×\/→—·-]+$/.test(text)) continue;
        if (tag.includes('data-no-i18n') || tag.includes('data-user-content')) continue;
        if (text in en) continue;
        leaks.push(text);
      }
    }
    expect(leaks).toEqual([]);
  });

  it('falls through to English for a missing key rather than showing a blank', () => {
    const t = code.slice(code.indexOf('function T(text)'), code.indexOf('function icTranslate'));
    expect(t).toContain('return s;');
    expect(t).toContain('hasOwnProperty.call(IC_DICT, s)');
  });
});

// ── the platform around it ───────────────────────────────────────────────────

describe('the platform owner reaches the city from the landing, and nobody else reaches it at all', () => {
  const app = read(APP_JS);

  it('is the fourth room on the platform owner landing', () => {
    expect(app).toContain('oh-card--city');
    expect(app).toContain('oh-cards--core');
    expect(app).not.toContain('oh-cards--three');
    expect(app).not.toContain('oh-cards--four');
    // The four rooms take the outer columns; the city has the second row's
    // far track, which is still a full sibling track and not a subordinate one.
    expect(read(APP_CSS)).toContain('"vault  core  city"');
  });

  it('shows a real status on the card rather than a decorative one', () => {
    const fn = app.slice(app.indexOf('function _fillCityStatus'), app.indexOf('function _fillCityStatus') + 1800);
    expect(fn).toContain('/system/infrastructure/health');
    expect(fn).not.toMatch(/Math\.random|'Healthy'\s*;/);
  });

  it('is registered as a page exactly once, in every list a page must be in', () => {
    expect(app).toContain("'infrastructure-city': 1");
    expect(app).toContain("case 'pg-infrastructure-city'");
    expect(app).toContain('renderInfrastructureCityHTML');
    // Membership in the allow-list is asserted against the real object, not by
    // string proximity — a proxy that breaks the moment a sibling is added.
    const allowStart = app.indexOf('var _ALLOWED_PAGES = {');
    expect(allowStart).toBeGreaterThan(-1);
    expect(app.slice(allowStart, app.indexOf('};', allowStart))).toContain("'infrastructure-city': 1");
  });

  it('loads its stylesheet and script once each', () => {
    const index = read(INDEX);
    expect((index.match(/infrastructure-city\.css/g) || [])).toHaveLength(1);
    expect((app.match(/infrastructure-city\.js/g) || []).length).toBeGreaterThanOrEqual(1);
  });

  it('closes the stream when the page is left', () => {
    // A live stream left running behind a navigated-away page is a socket the
    // platform pays for and nobody reads.
    expect(app).toContain('ic-city-open');
    const src = codeOf(read(CITY_JS));
    expect(src).toContain('function stopStream');
    expect(src).toMatch(/unmount|teardown|stopStream\(\)/);
  });
});
