/**
 * tests/source-core.unit.test.ts
 *
 * SOURCE CORE — where every input the platform holds came from.
 *
 * SIX PROPERTIES, AND THEY ARE THE WHOLE REASON THIS MODULE IS ALLOWED TO CLAIM
 * IT SHOWS A PROVENANCE MAP:
 *
 *   · It DISCOVERS nothing. Every source is composed from a registry that
 *     already exists and is already the authority for its half — the Data
 *     Fabric's source registry, the infrastructure manifest generated by
 *     reading the repository, and the live health signals. A third discovery
 *     mechanism would give the platform a third opinion about itself, and three
 *     opinions drift.
 *
 *   · It INVENTS no number. There is no source count, sync timestamp, data
 *     rate, version or health value in this build that a registry did not
 *     measure. Where nothing measured it the answer is one of five honest words
 *     — UNKNOWN, NOT INSTRUMENTED, NOT CONNECTED, DISCONNECTED, FUTURE — and
 *     they mean five different things.
 *
 *   · It LEAKS nothing. Provenance METADATA travels and nothing else: no
 *     environment value, connection string, key, token, credential, private
 *     email, medical note or anything a user typed. The registry it composes
 *     never reads a secret in the first place.
 *
 *   · It ADMITS what it does not know. Thirty-one mounted routers accept writes
 *     and own no registered event prefix. A provenance map that omitted them
 *     would be claiming the platform knows where all its data comes from, and
 *     it does not. They are listed, and listed as what they are.
 *
 *   · It CHANGES nothing. Six reads, no writes, on the whole router.
 *
 *   · It is GUARDED by the platform. The same `assertPlatformOwner` the other
 *     three platform rooms use, applied to the router rather than to the
 *     navigation.
 *
 * The frontend half is asserted by reading the source, for the same reason the
 * City's and the Vault's suites do: these are structural claims — "no second
 * source list exists", "no second stream is opened" — and a rendering test
 * would prove them only for the one path it happened to walk.
 */

import fs from 'fs';
import path from 'path';

const ROOT = path.join(__dirname, '..');
const SC_JS = path.join(ROOT, 'public/source-core/source-core.js');
const SC_CSS = path.join(ROOT, 'public/source-core/source-core.css');
const I18N_DIR = path.join(ROOT, 'public/source-core/i18n');
const APP_JS = path.join(ROOT, 'public/app.js');
const APP_CSS = path.join(ROOT, 'public/app.css');
const INDEX = path.join(ROOT, 'public/index.html');
const SERVICE_TS = path.join(ROOT, 'src/sources/source-registry.service.ts');
const ROUTES_TS = path.join(ROOT, 'src/routes/sources.routes.ts');
const LANE_TS = path.join(ROOT, 'src/fabric/registry/lane-activity.ts');
const DISCOVER = path.join(ROOT, 'scripts/infrastructure-discover.js');
const MANIFEST = path.join(ROOT, 'src/infra/generated/infrastructure-manifest.json');

const read = (p: string) => fs.readFileSync(p, 'utf8');

/**
 * The file with its comments removed.
 *
 * Several assertions below are of the form "this word never appears". Every one
 * of these files explains at length WHY a credential can never reach this
 * layer, so a naive search finds the word in the paragraph promising it is
 * absent. Stripping comments first is the difference between testing the code
 * and testing the prose about the code.
 */
const codeOf = (src: string) => src
  .replace(/\/\*[\s\S]*?\*\//g, ' ')
  .split('\n').map((l) => l.replace(/(^|[^:'"\\])\/\/.*$/, '$1')).join('\n');

/** One function's body, matched by braces rather than by a fixed window. */
const fnBody = (src: string, name: string): string => {
  const at = src.indexOf('function ' + name);
  if (at < 0) return '';
  let i = src.indexOf('{', at);
  let depth = 0;
  for (let j = i; j < src.length; j++) {
    if (src[j] === '{') depth++;
    else if (src[j] === '}') { depth--; if (!depth) return src.slice(i, j + 1); }
  }
  return src.slice(i);
};

// ── it composes, it does not discover ────────────────────────────────────────

describe('Source Core composes registries that already exist', () => {
  const svc = read(SERVICE_TS);
  const code = codeOf(svc);

  it('reads the Fabric source registry rather than listing domains itself', () => {
    expect(code).toContain("from '../fabric/registry/source-registry'");
    expect(code).toContain('fabricSources()');
  });

  it('reads the infrastructure manifest rather than listing components itself', () => {
    expect(code).toContain("from '../infra/infrastructure-registry.service'");
    expect(code).toContain('manifestOrNull()');
  });

  it('reads the live health signals rather than deciding health itself', () => {
    expect(code).toContain("from '../infra/infrastructure-health.service'");
    expect(code).toContain('infrastructureSignals()');
  });

  it('holds no hand-written list of sources, components or technologies', () => {
    // A literal array of service names in this file would be a fourth opinion
    // about what the platform is made of. The only arrays here are the ones
    // that map a taxonomy — types, states, districts to include — never the
    // inventory itself.
    expect(code).not.toMatch(/const\s+(SOURCES|COMPONENTS|SERVICES|TECHNOLOGIES)\s*[:=]\s*\[/);
  });

  it('extracts the Fabric lane reading rather than copying it', () => {
    // `laneActivity()` was private to fabric.routes.ts. Two callers with two
    // copies is two answers to "when did this source last produce", so it was
    // moved to one module both of them import.
    const lane = read(LANE_TS);
    expect(lane).toContain('export function laneActivity');
    expect(codeOf(read(ROUTES_TS))).toContain("from '../fabric/registry/lane-activity'");
    expect(codeOf(read(path.join(ROOT, 'src/routes/fabric.routes.ts'))))
      .toContain("from '../fabric/registry/lane-activity'");
  });

  it('adds no Prisma model and no migration — this is a view, not a store', () => {
    const schema = read(path.join(ROOT, 'prisma/schema.prisma'));
    expect(schema).not.toMatch(/model\s+(Source|PlatformSource|SourceRegistry|DataSource)\s*\{/);
    expect(codeOf(read(ROUTES_TS))).not.toContain('prisma.');
  });
});

// ── the vocabulary: five kinds of "we do not know" ───────────────────────────

describe('Source Core invents no number and no state', () => {
  const svc = read(SERVICE_TS);
  const code = codeOf(svc);
  const front = codeOf(read(SC_JS));

  it('keeps NOT_INSTRUMENTED apart from healthy', () => {
    expect(code).toContain("NOT_INSTRUMENTED");
    // The health union has to carry all eight words, or two of them collapse.
    for (const w of ['HEALTHY', 'WARNING', 'CRITICAL', 'DELAYED', 'DISCONNECTED',
      'UNKNOWN', 'NOT_INSTRUMENTED', 'FUTURE']) {
      expect(code).toContain(`'${w}'`);
    }
  });

  it('keeps connection state apart from health, because they answer differently', () => {
    for (const w of ['LIVE', 'CONNECTED', 'NOT_CONFIGURED', 'NOT_CONNECTED', 'UNVERIFIED']) {
      expect(code).toContain(`'${w}'`);
    }
  });

  it('turns each state into exactly one colour, in exactly one place', () => {
    const kind = fnBody(front, 'stateKind');
    expect(kind).toContain('HEALTHY');
    expect(kind).toContain('NOT_INSTRUMENTED');
    expect(kind).toContain('FUTURE');
    // And nothing else may turn a state into a class name. `stateLabel` maps
    // the same eight words to WORDS, which is a different job and correctly
    // lives beside it; what must not exist is a second opinion about colour.
    // So: every health/connection class in the module is built from
    // `stateKind(...)` and never from a literal.
    const classSites = [...front.matchAll(/sc-(?:chip|src)--' \+ ([A-Za-z_$][\w$]*)\(/g)]
      .map((m) => m[1]);
    expect(classSites.length).toBeGreaterThan(3);
    expect([...new Set(classSites)]).toEqual(['stateKind']);
    expect(front).not.toMatch(/sc-(?:chip|src)--(?:ok|warn|crit|off|none|unver|future)'/);
  });

  it('renders a measured zero as 0 and an unmeasured figure as an em dash', () => {
    const num = fnBody(front, 'num');
    expect(num).toContain("return '—'");
    expect(num).toContain("typeof n !== 'number'");
    // `has()` is absence, not falsiness: 0 is present.
    expect(fnBody(front, 'has')).toContain('v !== null && v !== undefined');
  });

  it('gives every em dash a reason a reader can hover', () => {
    expect(fnBody(front, 'absent')).toContain('title=');
    expect(front).toContain("absent(T('Not measured for this source.'))");
    expect(front).toContain("absent(T('Nothing recorded from this source.'))");
  });

  it('never fabricates a rate, a sync time or a version in the frontend', () => {
    expect(front).not.toMatch(/Math\.random/);
    expect(front).not.toMatch(/\bnew Date\(\)\s*[-+]/);
    // No figure is composed in the browser; each is read off the payload.
    expect(front).not.toMatch(/eventsPerMinute\s*=\s*[0-9]/);
  });

  it('reports a measured zero for a registered source that produced nothing', () => {
    // Not NOT_INSTRUMENTED — that is a different answer. The distinction is
    // made in the route, where the reading is taken.
    const routes = codeOf(read(ROUTES_TS));
    expect(routes).toContain('eventsPerMinute: seen ? seen.count : 0');
    expect(routes).toContain('lastEventAt: seen ? seen.lastAt : null');
  });
});

// ── it leaks nothing ─────────────────────────────────────────────────────────

describe('Source Core exposes provenance metadata and nothing else', () => {
  const svc = codeOf(read(SERVICE_TS));
  const routes = codeOf(read(ROUTES_TS));
  const front = codeOf(read(SC_JS));

  it('never reads an environment value into a payload', () => {
    for (const src of [svc, routes]) {
      expect(src).not.toMatch(/process\.env\[/);
      expect(src).not.toMatch(/process\.env\.[A-Z_]+/);
    }
  });

  it('names no credential, connection string or token field', () => {
    for (const src of [svc, routes, front]) {
      expect(src).not.toMatch(/DATABASE_URL|REDIS_URL|ANTHROPIC_API_KEY|STRIPE_SECRET/);
      expect(src).not.toMatch(/\b(password|passwordHash|secret|apiKey|accessToken|refreshToken)\b/i);
    }
  });

  it('carries the KIND of credential a source uses, never the credential', () => {
    expect(read(SERVICE_TS)).toContain('authMethod');
    expect(svc).not.toMatch(/authValue|credentialValue|keyValue/);
  });

  it('says so on the panel that shows the most about one source', () => {
    expect(front).toContain('Provenance metadata only. No environment value, credential or user data is available to this panel.');
  });

  it('carries no club, player, user or medical record', () => {
    for (const src of [svc, routes]) {
      expect(src).not.toMatch(/prisma\.(user|player|club|medical|injury)/i);
    }
  });

  it('proves the manifest it composes carries no secret-shaped value', () => {
    const manifest = read(MANIFEST);
    expect(manifest).not.toMatch(/postgres(ql)?:\/\/[^"]*:[^"@]*@/);
    expect(manifest).not.toMatch(/\bsk-[A-Za-z0-9_-]{16,}/);
    expect(manifest).not.toMatch(/\b[A-Za-z0-9_-]{24,}\.[A-Za-z0-9_-]{16,}\.[A-Za-z0-9_-]{16,}\b/);
  });
});

// ── authorization ────────────────────────────────────────────────────────────

describe('Source Core is the platform owner\'s, and the server is what says so', () => {
  const routes = read(ROUTES_TS);
  const code = codeOf(routes);

  it('authenticates every request on the router, not per route', () => {
    expect(code).toContain('router.use(authenticate)');
  });

  it('asserts platform owner on the router, using the platform\'s own guard', () => {
    expect(code).toContain('assertPlatformOwner');
    expect(code).toContain("from '../platform/system.service'");
    // The guard is mounted before any handler, so a route added later cannot
    // be added outside it.
    const guardAt = code.indexOf('assertPlatformOwner');
    const firstGet = code.indexOf("router.get(");
    expect(guardAt).toBeGreaterThan(-1);
    expect(guardAt).toBeLessThan(firstGet);
  });

  it('does not rely on hidden navigation', () => {
    // The allow-list in app.js is convenience. Removing it would not open the
    // API, and the comment at that site says so.
    const app = read(APP_JS);
    expect(app).toContain("'source-core': 1,");
    expect(app).toContain('guarded by assertPlatformOwner on the server');
  });

  it('serves six reads and no writes at all', () => {
    const gets = (code.match(/router\.get\(/g) || []).length;
    expect(gets).toBe(6);
    expect(code).not.toMatch(/router\.(post|put|patch|delete)\(/);
  });

  it('is mounted under the platform owner\'s own path', () => {
    const index = codeOf(read(path.join(ROOT, 'src/routes/index.ts')));
    expect(index).toContain("'/system/sources'");
    expect(index).toContain('sourcesRoutes');
  });

  it('opens no second stream over signals the city already streams', () => {
    expect(codeOf(read(SC_JS))).not.toContain('EventSource');
    expect(code).not.toContain('text/event-stream');
  });
});

// ── the taxonomy, and the uncomfortable fifth origin ─────────────────────────

describe('Source Core admits the sources the platform does not track', () => {
  const svc = read(SERVICE_TS);
  const code = codeOf(svc);
  const disc = read(DISCOVER);

  it('names unregistered intake as its own kind rather than hiding it', () => {
    expect(code).toContain("'UNREGISTERED_INTAKE'");
  });

  it('counts a router as intake only when it can actually RECEIVE', () => {
    // A router that declares no write verb is a read surface. `/home` declares
    // none and must drop out; `/devices` declares six and must stay. The rule
    // is a property of the router, read from the file, not a hand-kept list.
    expect(code).toContain('if (!mt.writes) return false');
    expect(disc).toMatch(/router\\\.\(\?:\?post\|put\|patch\|delete\)|post\|put\|patch\|delete/);
    expect(disc).toContain('writes');
    expect(disc).toContain('reads');
  });

  it('records the write and read verb counts in the manifest, so the rule is evidence', () => {
    const m = JSON.parse(read(MANIFEST));
    const mounts = m.mounts || [];
    expect(Array.isArray(mounts)).toBe(true);
    expect(mounts.length).toBeGreaterThan(20);
    for (const mt of mounts) {
      expect(typeof mt.path).toBe('string');
      expect(typeof mt.writes).toBe('number');
      expect(typeof mt.reads).toBe('number');
    }
    const home = mounts.find((x: { path: string }) => x.path === '/home');
    if (home) expect(home.writes).toBe(0);
    const devices = mounts.find((x: { path: string }) => x.path === '/devices');
    if (devices) expect(devices.writes).toBeGreaterThan(0);
  });

  it('keeps a future source out of every live count', () => {
    expect(code).toContain("sourceType === 'FUTURE'");
    expect(code).toContain("live: count((s) => s.health === 'HEALTHY')");
  });

  it('grades consequence in three degrees rather than one alarm', () => {
    expect(code).toContain("'DIRECTLY_AFFECTED'");
    expect(code).toContain("'DEPENDENT'");
    expect(code).toContain("'POTENTIALLY_AFFECTED'");
  });

  it('gives every source a file that proves it exists', () => {
    expect(svc).toContain('evidence: string');
    // A lineage stage carries its own evidence too, so a stage cannot be drawn
    // without one.
    expect(svc).toMatch(/interface LineageStage[\s\S]*?evidence: string;/);
  });
});

// ── the flow, drawn ──────────────────────────────────────────────────────────

describe('the flow view draws five stages with the core third of five', () => {
  const front = read(SC_JS);
  const code = codeOf(front);
  const css = read(SC_CSS);

  it('puts the core between intake and processing, not at an end', () => {
    const flow = fnBody(code, 'flowHtml');
    const iOrigins = flow.indexOf('sc-stage--origins');
    const iIntake = flow.indexOf('sc-stage--intake');
    const iCore = flow.indexOf('sc-core-wrap');
    const iProc = flow.indexOf('sc-stage--processing');
    const iCons = flow.indexOf('sc-stage--consumers');
    expect(iOrigins).toBeGreaterThan(-1);
    expect(iIntake).toBeGreaterThan(iOrigins);
    expect(iCore).toBeGreaterThan(iIntake);
    expect(iProc).toBeGreaterThan(iCore);
    expect(iCons).toBeGreaterThan(iProc);
  });

  it('keeps the core central when the row becomes a column', () => {
    // Below 1280 the five stages stack. Third of five is still the middle, so
    // the architecture is preserved rather than crushed.
    expect(css).toContain('@media (max-width: 1280px)');
    expect(css).toContain('.sc-conduit { flex-direction: column; }');
    expect(css).toContain('grid-template-columns: minmax(0, 620px)');
  });

  it('animates a conduit only when the registry measured live throughput', () => {
    expect(code).toContain("var carry = counts.live > 0 ? 'live' : 'idle';");
    expect(code).toContain('+ conduit(carry)');
    expect(code).not.toContain("conduit('ok')");
    expect(css).toContain('.sc-conduit--live .sc-conduit-line');
    expect(css).toContain('.sc-conduit--idle .sc-conduit-line { background: rgba(91, 100, 128, .34); }');
    expect(css).toContain('@keyframes sc-carry');
  });

  it('stops that motion for a reader who asked for less of it', () => {
    expect(css).toContain('@media (prefers-reduced-motion: reduce)');
    const block = css.slice(css.indexOf('@media (prefers-reduced-motion: reduce)'));
    expect(block).toContain('.sc-conduit--live .sc-conduit-line { animation: none;');
  });

  it('paints when the page-render registry calls it with no argument', () => {
    // The registry calls every renderer as `fn()`. A renderer that only accepts
    // an explicit host mounts the page and leaves it blank — which is what this
    // module did the first time a browser opened it, with no error anywhere.
    expect(read(SC_JS)).toContain("host = host || document.getElementById('sc-root');");
    // And the element it looks for is the one the page template creates.
    expect(read(APP_JS)).toContain('<div id="sc-root"></div>');
  });

  it('bounds the diagram by the viewport rather than by its longest column', () => {
    // Left unbounded the plates grow to the tallest column and run off the
    // bottom of the screen; bounded without an explicit row, the auto row is
    // sized by content and overflows the clamp anyway.
    expect(css).toContain('max-height: calc(100dvh - 206px); min-height: 420px;');
    expect(css).toContain('grid-template-rows: minmax(0, 1fr);');
  });

  it('leaves that model entirely when the flow becomes a column', () => {
    // Constrained AND stacked, the tracks are squeezed under their content and
    // the core — centred in its own track — spills over four other stages.
    const col = css.slice(css.indexOf('@media (max-width: 1280px)'));
    expect(col).toContain('.sc-flow { flex: 0 0 auto; display: block; }');
    expect(col).toContain('flex: none; max-height: none; min-height: 0; grid-template-rows: none;');
    expect(col).toContain('.sc-core-wrap { align-items: stretch; }');
  });

  it('never composes a title by concatenating data into it', () => {
    // A title built by concatenation is a key the catalogue can never hold.
    // The module name goes beside the title as data, not into it.
    expect(code).not.toMatch(/panel\('[^']*'\s*\+/);
    expect(code).toContain('sc-panel-tag');
    expect(code).toContain('data-no-i18n');
  });
});

// ── nothing moves that the reader did not move ───────────────────────────────

describe('the Source Core holds still', () => {
  const css = read(SC_CSS);
  const code = codeOf(read(SC_JS));

  it('is a fixed-height column whose body scrolls inside itself', () => {
    expect(css).toContain('.sc-shell { display: flex; height: 100vh;');
    expect(css).toContain('scrollbar-gutter: stable');
  });

  it('floats the inspector rather than pushing the page', () => {
    expect(css).toMatch(/\.sc-insp \{[^}]*position: fixed/);
    expect(css).toMatch(/\.sc-insp-scrim \{[^}]*position: fixed/);
    // Entering animates opacity and transform only — nothing that reflows.
    expect(css).toContain('@keyframes sc-slide { from { opacity: 0; transform: translateX(14px); }');
  });

  it('repaints the one region that changed rather than the whole page', () => {
    const repaint = fnBody(code, 'repaintBody');
    expect(repaint).toContain("querySelector('#sc-body')");
    expect(repaint).toContain('contentHtml()');
  });

  it('stands a skeleton in for content at the size the content will be', () => {
    expect(code).toContain('function skeleton(');
    expect(css).toContain('.sc-skel-row { height: 40px;');
  });

  it('carries an escape hatch rather than crushing panels on a small screen', () => {
    expect(css).toContain('@media (max-width: 980px), (max-height: 620px)');
    expect(css).toContain('body.sc-core-open { overflow: auto; }');
    expect(css).toContain('.sc-shell { display: block; height: auto;');
  });

  it('keeps the language menu above the panels below it', () => {
    // Every panel carries a backdrop-filter, which creates a stacking context.
    expect(css).toMatch(/\.sc-top \{[\s\S]*?z-index: 40;/);
  });
});

// ── the runtime contract guard ───────────────────────────────────────────────

describe('a malformed payload fails loudly rather than drawing an empty room', () => {
  const code = codeOf(read(SC_JS));

  it('names the fields it cannot draw without', () => {
    expect(code).toContain('var REQUIRED =');
    expect(code).toContain("registry:");
    expect(code).toContain("flow:");
  });

  it('reports absence and never reports a measured empty as a fault', () => {
    const miss = fnBody(code, 'missingFields');
    expect(miss).toContain('=== undefined');
    expect(miss).toContain('=== null');
    expect(miss).not.toContain('.length === 0');
  });

  it('says CONTRACT ERROR with the endpoint and the missing fields', () => {
    const err = fnBody(code, 'contractError');
    expect(err).toContain("T('CONTRACT ERROR')");
    expect(err).toContain('endpoint');
    expect(err).toContain("missing.join(', ')");
  });

  it('is covered by the repository\'s contract suite in both directions', () => {
    const contracts = read(path.join(ROOT, 'src/contracts/owner-api.contracts.ts'));
    for (const e of ['/system/sources', '/system/sources/health', '/system/sources/flow',
      '/system/sources/fabric:users', '/system/sources/fabric:users/consumers',
      '/system/sources/fabric:users/lineage']) {
      expect(contracts).toContain(`endpoint: '${e}'`);
    }
    // And pinned to the interfaces, so a renamed field fails the build.
    expect(contracts).toContain('Exact<z.infer<typeof PlatformSourceSchema>, PlatformSource>');
  });
});

// ── localisation ─────────────────────────────────────────────────────────────

describe('the Source Core speaks English, German and Arabic — and only those', () => {
  const en = JSON.parse(read(path.join(I18N_DIR, 'en.json')));
  const de = JSON.parse(read(path.join(I18N_DIR, 'de.json')));
  const ar = JSON.parse(read(path.join(I18N_DIR, 'ar.json')));
  const src = read(SC_JS);
  const code = codeOf(src);

  it('ships exactly three catalogues', () => {
    expect(fs.readdirSync(I18N_DIR).sort()).toEqual(['ar.json', 'de.json', 'en.json']);
  });

  it('declares the three locales and their directions', () => {
    expect(code).toContain("[['en', 'English', 'ltr'], ['de', 'Deutsch', 'ltr'], ['ar', 'العربية', 'rtl']]");
  });

  it('has a German and an Arabic entry for every English key', () => {
    const keys = Object.keys(en);
    expect(keys.length).toBeGreaterThan(200);
    expect(Object.keys(de).sort()).toEqual([...keys].sort());
    expect(Object.keys(ar).sort()).toEqual([...keys].sort());
  });

  it('actually translates — nothing is left in English', () => {
    const leftInEnglish = Object.entries(ar).filter(([k, v]) => v === k);
    expect(leftInEnglish).toEqual([]);
    for (const [k, v] of Object.entries(de)) {
      expect(typeof v).toBe('string');
      expect((v as string).length).toBeGreaterThan(0);
      void k;
    }
  });

  it('writes Arabic in Arabic script', () => {
    for (const k of ['Source Core', 'Source Flow', 'Data Lineage', 'Unregistered intake',
      'Not instrumented', 'Origin & Provenance Layer', 'If this fails']) {
      expect(ar[k]).toMatch(/[\u0600-\u06FF]/);
    }
  });

  it('sets the document direction from the locale, so Arabic renders RTL', () => {
    expect(code).toContain("host.setAttribute('dir', SC_DIR)");
    expect(code).toContain('SC_DIR = l[2]');
  });

  it('lays the shell out for RTL rather than only flipping the text', () => {
    const css = read(SC_CSS);
    expect(css).toContain('#pg-source-core[dir="rtl"] .sc-shell { flex-direction: row-reverse; }');
    expect(css).toContain('border-inline-end');
    expect(css).toContain('inset-inline-end');
    expect(css).toContain('padding-inline-start');
    // The arrowhead on a conduit points inline-end, and `clip-path` has no
    // logical form, so the direction is mirrored explicitly.
    expect(css).toContain('#pg-source-core[dir="rtl"] .sc-conduit-head { transform: scaleX(-1); }');
    // The inspector is pinned to the inline end, so in Arabic it enters left.
    expect(css).toContain('@keyframes sc-slide-rtl');
    expect(css).toContain('#pg-source-core[dir="rtl"] .sc-insp { animation-name: sc-slide-rtl; }');
    // Every layer edge is an inset shadow, which has no logical form either.
    expect(css).toContain('#pg-source-core[dir="rtl"] .sc-olayer');
  });

  it('lets a name carry its own direction, so a route path is not reversed', () => {
    const css = read(SC_CSS);
    // `/billing` inside an Arabic paragraph renders as `billing/`: the leading
    // slash is bidi-neutral and is laid out at the paragraph's end. `plaintext`
    // takes each name's base direction from its own first strong character, so
    // an identifier reads LTR and an Arabic name reads RTL — with no list of
    // which names are identifiers to keep in step with anything.
    expect(css).toContain('unicode-bidi: plaintext;');
    const rule = css.slice(css.indexOf('.sc-src-name, .sc-mech-name'), css.indexOf('unicode-bidi: plaintext;'));
    for (const cls of ['.sc-src-name', '.sc-td-name', '.sc-td-origin', '.sc-type', '.sc-impact-name']) {
      expect(rule).toContain(cls);
    }
    // And the Arabic "more" label carries no leading sign, which the same
    // reordering would put on the wrong side of the number.
    expect(ar['+%d more']).not.toMatch(/^\+/);
    expect(ar['+%d more']).toMatch(/%d/);
  });

  it('never translates a technology name, a source id or a version', () => {
    const walker = code.slice(code.indexOf('function scTranslate'), code.indexOf('function languageSwitchHtml'));
    expect(walker).toContain("hasAttribute('data-no-i18n')");
    expect(walker).toContain("hasAttribute('data-user-content')");
    // Versions, event types, ids and counts are all marked at the call site.
    expect(code).toContain('<span class="sc-type" data-no-i18n>');
    expect(code).toContain('<span class="sc-src-count" data-no-i18n>');
    expect(code).toContain('<div class="sc-core-title" data-no-i18n>Familista Source Core</div>');
  });

  it('keeps its catalogue out of the platform\'s club-facing locale files', () => {
    const app = read(APP_JS);
    expect(app).toContain('<div class="page" id="pg-source-core" data-no-i18n>');
    const clubCatalogue = JSON.parse(read(path.join(ROOT, 'public/i18n/catalogue/de-DE.json')));
    expect(clubCatalogue['Source Core']).toBeUndefined();
    expect(clubCatalogue['Unregistered intake']).toBeUndefined();
  });

  it('is not scanned by the platform extractor, and that is deliberate', () => {
    const extractor = read(path.join(ROOT, 'scripts/i18n-extract.js'));
    const sources = extractor.slice(extractor.indexOf('const SOURCES = ['), extractor.indexOf('const OUT'));
    expect(sources).not.toContain('source-core');
  });

  it('has a catalogue entry for every string the module asks it to translate', () => {
    const asked = new Set<string>();
    for (const m of code.matchAll(/\bT\(\s*'((?:[^'\\]|\\.)*)'\s*\)/g)) asked.add(m[1].replace(/\\'/g, "'"));
    // And the T(variable) call sites, fed from these lists. A literal-only scan
    // cannot see them, and that is exactly the gap that shipped four English
    // labels inside an Arabic page once before.
    const listOf = (re: RegExp) => (code.match(re) || [''])[0];
    const lists = [
      listOf(/var SECTIONS = \[[\s\S]*?\];/),
      listOf(/var GROUP_LABEL = \{[\s\S]*?\};/),
      listOf(/var TYPE_LABEL = \{[\s\S]*?\};/),
      listOf(/var INTAKE_LABEL = \{[\s\S]*?\};/),
      listOf(/var LAYER_LABEL = \{[\s\S]*?\};/),
      listOf(/var STAGE_LABEL = \{[\s\S]*?\};/),
    ];
    for (const block of lists) {
      expect(block.length).toBeGreaterThan(0);
      for (const m of block.matchAll(/'((?:[^'\\]|\\.)*)'/g)) {
        const v = m[1].replace(/\\'/g, "'");
        if (/^[A-Z]/.test(v) && /[a-z ]/.test(v)) asked.add(v);
      }
    }
    // The panel and empty-state titles, which are translated inside the helper.
    for (const fn of ['panel', 'emptyState', 'row', 'idRow']) {
      for (const m of code.matchAll(new RegExp('\\b' + fn + "\\(\\s*'((?:[^'\\\\]|\\\\.)*)'", 'g'))) {
        const v = m[1].replace(/\\'/g, "'");
        if (v) asked.add(v);
      }
    }
    expect(asked.size).toBeGreaterThan(100);
    expect([...asked].filter((k) => !(k in en))).toEqual([]);
  });

  it('translates the registry\'s descriptive names and leaves its technology names alone', () => {
    // The map draws names that come from a registry, not from the source file,
    // so the ratchets above cannot see them. This is the ratchet for those.
    //
    // The mechanism is the catalogue itself: a name with an entry is
    // translated, a name without one falls through `T` unchanged. There is no
    // second list of "do not translate" to keep in step with anything —
    // absence IS the instruction, which is why a technology can never be
    // translated by accident.
    expect(code).toContain('esc(T(s.name))');
    expect(code).toContain('esc(T(s.origin))');
    expect(code).toContain('esc(T(st.label))');

    // A descriptive domain or component name must be translated.
    for (const name of ['Users', 'Players', 'Matches', 'Medical', 'Object Storage',
      'Durable Outbox', 'Historical Event Store', 'Unregistered intake']) {
      expect(Object.prototype.hasOwnProperty.call(en, name)).toBe(true);
      expect(ar[name]).toMatch(/[\u0600-\u06FF]/);
    }
    // A technology or product name must NOT be, in any of the three.
    for (const name of ['PostgreSQL', 'TypeScript', 'Node.js', 'Prisma', 'Redis',
      'Express', 'Zod', 'Jest', 'Data Fabric', 'Data Vault', 'Anthropic', 'Stripe']) {
      expect({ name, inCatalogue: Object.prototype.hasOwnProperty.call(en, name) })
        .toEqual({ name, inCatalogue: false });
    }
  });

  it('leaves no prose in the markup that the catalogue has never seen', () => {
    // A sentence written straight into the HTML is a sentence nothing
    // translates: if it is not in the catalogue it renders in English,
    // whatever the locale.
    const offenders: string[] = [];
    for (const m of code.matchAll(/>([^<>{}'"`]{8,})</g)) {
      const text = m[1].trim();
      if (!/[a-z]/.test(text) || !/^[A-Za-z]/.test(text)) continue;
      const before = code.slice(Math.max(0, m.index! - 220), m.index!);
      const tag = before.lastIndexOf('<');
      if (tag >= 0) {
        const open = before.slice(tag);
        if (open.includes('data-no-i18n') || open.includes('data-user-content')) continue;
      }
      if (!(text in en)) offenders.push(text);
    }
    expect(offenders).toEqual([]);
  });
});

// ── the landing, and where the fifth room sits on it ─────────────────────────

describe('SOURCE CORE is the middle of the landing, not the end of a row', () => {
  const app = read(APP_JS);
  const css = read(APP_CSS);

  it('is a card of its own on the platform owner\'s landing', () => {
    expect(app).toContain('data-page="source-core"');
    expect(app).toContain('<div class="oh-card-title">SOURCE CORE</div>');
  });

  it('sits in the geometric centre of the grid at every width', () => {
    expect(css).toContain('body.club-theme .oh-cards--core{');
    // Three columns: the core spans both rows in the middle track.
    expect(css).toContain('"system core  clubs"');
    expect(css).toContain('"vault  core  city"');
    // Two columns: the core takes the middle row.
    expect(css).toContain('"system clubs"');
    expect(css).toContain('"core   core"');
    // One column: third of five is still the middle.
    expect(css).toContain('grid-template-areas: "system" "clubs" "core" "vault" "city";');
  });

  it('carries a real summary or an honest absence, never a placeholder figure', () => {
    const fn = fnBody(app, '_fillSourceCoreStatus');
    expect(fn).toContain("'/system/sources/health'");
    expect(fn).toContain("d.state === 'NOT_GENERATED'");
    expect(fn).toContain('not instrumented: ');
    expect(fn).toContain("write('bad', 'Source registry unreachable')");
    // Nothing is written into the card before the platform has answered.
    expect(app).toContain('Reading source registry…');
  });

  it('is wired everywhere a page has to be wired, or it is only half a page', () => {
    expect(app).toContain("'source-core':                 ['renderFamilistaSourceCore'],");
    expect(app).toContain("case 'pg-source-core':");
    expect(app).toContain("'source-core':                 renderSourceCoreHTML,");
    expect(app).toContain("'source-core':'Source Core'");
    expect(app).toContain("document.body.classList.toggle('sc-core-open', page === 'source-core')");
    expect(app).toContain('teardownFamilistaSourceCore');
    expect(app).toContain("'infrastructure-city', 'source-core',");
    const index = read(INDEX);
    expect(index).toContain('/source-core/source-core.css');
    expect(index).toContain('/source-core/source-core.js');
  });

  it('takes the viewport the way the other three platform rooms do', () => {
    const scss = read(SC_CSS);
    expect(scss).toContain('body.sc-core-open .sidebar,');
    expect(scss).toContain('body.sc-core-open .topbar { display: none !important; }');
  });
});
