// Familista League — administration
// ─────────────────────────────────────────────────────────────────────────────
// The write side of the league, kept in its own file because
// familista-league.service.ts is the read side and is asserted to contain no
// writes at all. A club reading the table it plays in and an administrator
// changing who is in that table are different permissions, and keeping them in
// different files is what makes the first one safe to expose to everybody.
//
// Three things happen here and nothing else:
//
//   participation   who is in the league — always a reference to an existing
//                   Team, never a copy of one. No name, crest, squad or player
//                   is duplicated: the league stores a team id and reads the
//                   rest from the club's own record every time it draws.
//
//   the calendar    generated by the competition engine's round-robin, which
//                   already existed and is not reimplemented here. Every fixture
//                   it produces is then given a real Match — the same Match the
//                   Match Centre opens — so a league match and a match are one
//                   row, not two systems that have to be kept in step.
//
//   the result      when a Match reaches full time anywhere in the platform, the
//                   fixture it belongs to takes its score and the table is
//                   rebuilt by the engine that owns that arithmetic. Nobody
//                   types a league result in twice.
//
// Who may call any of it: a platform administrator. A league owned by no club
// has no club administrator, and `_assertCompOwner` in the competition engine
// already reaches the same conclusion — a null owner matches nobody's clubId, so
// only SUPER_ADMIN passes. This file states that rule directly rather than
// arriving at it by accident.

import { MatchStatus, Prisma, CompetitionType } from '@prisma/client';
import { prisma } from '../config/database';
import { BadRequestError, ForbiddenError, NotFoundError } from '../utils/errors';
import { eligibilityOf, eligibleTeamWhere } from './league-eligibility';
import {
  generateRoundRobinFixtures,
  rebuildStandingsUnchecked,
  type CompActor,
} from './competition.service';

export interface LeagueActor {
  userId: string;
  clubId: string;
  role?: string;
}

/** Only a platform administrator may change who plays in the league. */
export function assertLeagueAdmin(actor: LeagueActor): void {
  if (actor.role !== 'SUPER_ADMIN') {
    throw new ForbiddenError('Managing Familista League participants requires a platform administrator');
  }
}

async function requirePlatformLeague(competitionId: string) {
  const comp = await prisma.competition.findFirst({ where: { id: competitionId, clubId: null } });
  if (!comp) throw new NotFoundError('Familista League');
  return comp;
}

// ─────────────────────────────────────────────────────────────────────────────
// Who is in it, and who could be
// ─────────────────────────────────────────────────────────────────────────────

export interface ParticipantRow {
  teamId: string;
  teamName: string;
  clubId: string;
  clubName: string;
  crestUrl: string | null;
  /** Completed league matches this team has played. Governs whether it can go. */
  playedMatches: number;
  /** False when the team has since been deactivated or is no longer a first team. */
  stillEligible: boolean;
}

export interface EligibleTeamRow {
  teamId: string;
  teamName: string;
  clubId: string;
  clubName: string;
  crestUrl: string | null;
  squadSize: number;
  participating: boolean;
}

export async function listParticipants(competitionId: string): Promise<ParticipantRow[]> {
  await requirePlatformLeague(competitionId);

  const entries = await prisma.competitionTeam.findMany({
    where: { competitionId },
    select: { teamId: true },
  });
  const teamIds = entries.map((e) => e.teamId);
  if (teamIds.length === 0) return [];

  const [teams, played] = await Promise.all([
    prisma.team.findMany({
      where: { id: { in: teamIds } },
      select: {
        id: true, name: true, kind: true, isActive: true, clubId: true,
        club: { select: { id: true, name: true, crestUrl: true, emblem: true } },
      },
    }),
    prisma.fixture.findMany({
      where: { competitionId, status: 'PLAYED' },
      select: { homeTeamId: true, awayTeamId: true },
    }),
  ]);

  const playCount = new Map<string, number>();
  for (const f of played) {
    playCount.set(f.homeTeamId, (playCount.get(f.homeTeamId) ?? 0) + 1);
    playCount.set(f.awayTeamId, (playCount.get(f.awayTeamId) ?? 0) + 1);
  }

  return teams
    .map((t) => ({
      teamId: t.id,
      teamName: t.name,
      clubId: t.clubId,
      clubName: t.club?.name ?? t.name,
      crestUrl: t.club?.crestUrl ?? t.club?.emblem ?? null,
      playedMatches: playCount.get(t.id) ?? 0,
      stillEligible: eligibilityOf({ kind: t.kind, isActive: t.isActive }).eligible,
    }))
    .sort((a, b) => a.clubName.localeCompare(b.clubName));
}

/**
 * Every team that could join, with the ones already in it flagged rather than
 * hidden — an administrator looking for a club wants to see that it is already
 * playing, not to wonder why it is missing.
 *
 * The eligibility rule is not written here. It comes from league-eligibility.ts,
 * so a new club's first team becomes selectable the moment the club is created,
 * with no code change anywhere.
 */
export async function listEligibleTeams(
  competitionId: string,
  opts: { search?: string; limit?: number } = {},
): Promise<EligibleTeamRow[]> {
  await requirePlatformLeague(competitionId);

  const search = (opts.search ?? '').trim();
  const where: Prisma.TeamWhereInput = {
    ...eligibleTeamWhere(),
    ...(search
      ? {
          OR: [
            { name: { contains: search, mode: 'insensitive' } },
            { club: { name: { contains: search, mode: 'insensitive' } } },
          ],
        }
      : {}),
  };

  const [teams, entered] = await Promise.all([
    prisma.team.findMany({
      where,
      select: {
        id: true, name: true, clubId: true,
        club: { select: { name: true, crestUrl: true, emblem: true } },
        _count: { select: { players: true } },
      },
      orderBy: [{ club: { name: 'asc' } }, { name: 'asc' }],
      take: Math.min(opts.limit ?? 50, 200),
    }),
    prisma.competitionTeam.findMany({ where: { competitionId }, select: { teamId: true } }),
  ]);

  const inLeague = new Set(entered.map((e) => e.teamId));
  return teams.map((t) => ({
    teamId: t.id,
    teamName: t.name,
    clubId: t.clubId,
    clubName: t.club?.name ?? t.name,
    crestUrl: t.club?.crestUrl ?? t.club?.emblem ?? null,
    squadSize: t._count.players,
    participating: inLeague.has(t.id),
  }));
}

// ─────────────────────────────────────────────────────────────────────────────
// Adding and removing a participant
// ─────────────────────────────────────────────────────────────────────────────

export async function addParticipant(
  actor: LeagueActor,
  competitionId: string,
  teamId: string,
): Promise<ParticipantRow[]> {
  assertLeagueAdmin(actor);
  await requirePlatformLeague(competitionId);

  const team = await prisma.team.findUnique({
    where: { id: teamId },
    select: { id: true, kind: true, isActive: true, clubId: true },
  });
  if (!team) throw new NotFoundError('Team');

  const verdict = eligibilityOf({ kind: team.kind, isActive: team.isActive });
  if (!verdict.eligible) {
    throw new BadRequestError(
      verdict.reason === 'NOT_FIRST_TEAM'
        ? 'Only a club first team can play in the Familista League'
        : 'That team is not active',
    );
  }

  const already = await prisma.competitionTeam.findUnique({
    where: { competitionId_teamId: { competitionId, teamId } },
    select: { id: true },
  });
  if (already) throw new BadRequestError('That team already plays in this season');

  // The participation row is a reference and a club attribution, and nothing
  // else: no name, no crest, no squad. Everything shown about this team is read
  // from the team and its club when the screen is drawn, so a rename or a new
  // crest appears in the league without anything here changing.
  await prisma.competitionTeam.create({
    data: { competitionId, teamId, clubId: team.clubId },
  });

  return listParticipants(competitionId);
}

export interface RemovalOutcome {
  removed: boolean;
  /** Fixtures deleted along with the participation, all of them unplayed. */
  fixturesRemoved: number;
  participants: ParticipantRow[];
}

/**
 * Remove a team from the season.
 *
 * Safe while the season is still only a plan: the team's unplayed fixtures go
 * with it. Refused the moment it has completed a league match, because taking it
 * out then would rewrite results that already happened and orphan the Match
 * Centre records of the clubs it played. That case needs a decision a person
 * makes — a void, a forfeit, a replacement — and this is not the place to guess
 * which.
 */
export async function removeParticipant(
  actor: LeagueActor,
  competitionId: string,
  teamId: string,
): Promise<RemovalOutcome> {
  assertLeagueAdmin(actor);
  await requirePlatformLeague(competitionId);

  const entry = await prisma.competitionTeam.findUnique({
    where: { competitionId_teamId: { competitionId, teamId } },
    select: { id: true },
  });
  if (!entry) throw new NotFoundError('League participant');

  const playedCount = await prisma.fixture.count({
    where: {
      competitionId,
      status: 'PLAYED',
      OR: [{ homeTeamId: teamId }, { awayTeamId: teamId }],
    },
  });
  if (playedCount > 0) {
    throw new BadRequestError(
      `This team has already played ${playedCount} league match(es). Removing it would rewrite completed results, so it needs a scheduling decision rather than a deletion.`,
    );
  }

  const fixtures = await prisma.fixture.findMany({
    where: { competitionId, OR: [{ homeTeamId: teamId }, { awayTeamId: teamId }] },
    select: { id: true, matchId: true },
  });

  for (const f of fixtures) await _deleteFixtureAndItsMatch(f.id, f.matchId);
  await prisma.competitionTeam.delete({ where: { id: entry.id } });
  await rebuildStandingsUnchecked(competitionId);

  return {
    removed: true,
    fixturesRemoved: fixtures.length,
    participants: await listParticipants(competitionId),
  };
}

/**
 * Drop a fixture, and the Match it was played as — but only when that Match
 * carries nothing anybody recorded. A match with a lineup, a timeline or a
 * player statistic is somebody's work, and it is unlinked rather than deleted.
 */
async function _deleteFixtureAndItsMatch(fixtureId: string, matchId: string | null): Promise<void> {
  await prisma.fixture.delete({ where: { id: fixtureId } });
  if (!matchId) return;

  const match = await prisma.match.findUnique({
    where: { id: matchId },
    select: {
      id: true, status: true,
      _count: {
        select: {
          lineups: true, timeline: true, events: true,
          playerStats: true, playerMatchStats: true, tacticalSnapshots: true,
        },
      },
    },
  });
  if (!match) return;

  const untouched =
    match.status === MatchStatus.SCHEDULED &&
    match._count.lineups === 0 &&
    match._count.timeline === 0 &&
    match._count.events === 0 &&
    match._count.playerStats === 0 &&
    match._count.playerMatchStats === 0 &&
    match._count.tacticalSnapshots === 0;
  if (untouched) await prisma.match.delete({ where: { id: matchId } });
}

// ─────────────────────────────────────────────────────────────────────────────
// The calendar
// ─────────────────────────────────────────────────────────────────────────────

export interface ScheduleOutcome {
  participants: number;
  matches: number;
  rounds: number;
  /** Matches created in the Match Centre for the fixtures, this run. */
  matchesLinked: number;
}

/**
 * Generate the season's fixtures from whoever is entered, then give every one of
 * them a real Match.
 *
 * The pairing arithmetic is the competition engine's `generateRoundRobinFixtures`
 * and is not repeated here: it already does the circle method, both legs, and
 * the round numbering, for any number of teams. Four teams give six rounds and
 * twelve matches because that is what a double round-robin between four teams
 * is — not because a four is written down anywhere.
 *
 * Refused once a match has been played, per the same reasoning as removing a
 * participant: regenerating a calendar that has results in it would throw those
 * results away.
 */
export async function rebuildSchedule(
  actor: LeagueActor,
  competitionId: string,
  opts: { startDate?: string; intervalDays?: number } = {},
): Promise<ScheduleOutcome> {
  assertLeagueAdmin(actor);
  const comp = await requirePlatformLeague(competitionId);

  const playedCount = await prisma.fixture.count({ where: { competitionId, status: 'PLAYED' } });
  if (playedCount > 0) {
    throw new BadRequestError(
      `Schedule adjustment required: ${playedCount} league match(es) have already been played, so the calendar cannot be regenerated automatically.`,
    );
  }

  const existing = await prisma.fixture.findMany({
    where: { competitionId },
    select: { id: true, matchId: true },
  });
  for (const f of existing) await _deleteFixtureAndItsMatch(f.id, f.matchId);

  const rules = (comp.rules ?? {}) as { format?: { startsOn?: string } };
  const startDate = opts.startDate ?? rules.format?.startsOn ?? new Date().toISOString().slice(0, 10);

  const compActor: CompActor = { userId: actor.userId, clubId: actor.clubId, role: actor.role };
  await generateRoundRobinFixtures(compActor, competitionId, startDate, opts.intervalDays ?? 7, false);

  const linked = await ensureFixtureMatches(competitionId);
  const fixtures = await prisma.fixture.findMany({ where: { competitionId }, select: { round: true } });
  const participants = await prisma.competitionTeam.count({ where: { competitionId } });
  await rebuildStandingsUnchecked(competitionId);

  return {
    participants,
    matches: fixtures.length,
    rounds: new Set(fixtures.map((f) => f.round).filter((r) => r != null)).size,
    matchesLinked: linked,
  };
}

/**
 * Give every fixture a Match, so that opening a league fixture opens the Match
 * Centre rather than a second thing that looks like it.
 *
 * The Match is owned by the home club — a Match row has one owning club, and the
 * home side is the one that stages the game — and carries the competition, its
 * name and its season, which is what tells everything downstream that this is a
 * Familista League match rather than a friendly.
 */
export async function ensureFixtureMatches(competitionId: string): Promise<number> {
  const comp = await requirePlatformLeague(competitionId);

  const fixtures = await prisma.fixture.findMany({
    where: { competitionId, matchId: null },
    select: { id: true, homeTeamId: true, awayTeamId: true, scheduledAt: true, venue: true, round: true },
  });
  if (fixtures.length === 0) return 0;

  const teamIds = [...new Set(fixtures.flatMap((f) => [f.homeTeamId, f.awayTeamId]))];
  const teams = await prisma.team.findMany({
    where: { id: { in: teamIds } },
    select: { id: true, name: true, clubId: true, club: { select: { name: true } } },
  });
  const byId = new Map(teams.map((t) => [t.id, t]));

  let created = 0;
  for (const f of fixtures) {
    const home = byId.get(f.homeTeamId);
    const away = byId.get(f.awayTeamId);
    if (!home || !away) continue;

    const match = await prisma.match.create({
      data: {
        clubId: home.clubId,
        teamId: home.id,
        // The names are written onto the Match because that is how a Match has
        // always recorded its sides; the league itself never reads them back —
        // it reads the team rows — so a later rename cannot leave the league
        // showing a stale name.
        homeTeam: home.club?.name ?? home.name,
        awayTeam: away.club?.name ?? away.name,
        isHome: true,
        competition: CompetitionType.LEAGUE,
        competitionName: comp.name,
        season: comp.season,
        scheduledAt: f.scheduledAt,
        venue: f.venue,
        status: MatchStatus.SCHEDULED,
      },
      select: { id: true },
    });
    await prisma.fixture.update({ where: { id: f.id }, data: { matchId: match.id } });
    created++;
  }
  return created;
}

/**
 * Move a fixture, and the match it is played as, together.
 *
 * §15's rule stated as code: there is one date, and it lives on both rows
 * because the Match Centre reads one and the league screen reads the other.
 * Changing it in one place and not the other is the duplication this whole task
 * exists to remove.
 */
export async function rescheduleFixture(
  actor: LeagueActor,
  fixtureId: string,
  scheduledAt: string,
  venue?: string | null,
): Promise<{ fixtureId: string; matchId: string | null; scheduledAt: string }> {
  assertLeagueAdmin(actor);

  const fixture = await prisma.fixture.findUnique({
    where: { id: fixtureId },
    select: { id: true, matchId: true, status: true, competitionId: true },
  });
  if (!fixture) throw new NotFoundError('Fixture');
  await requirePlatformLeague(fixture.competitionId);
  if (fixture.status === 'PLAYED') throw new BadRequestError('That match has already been played');

  const when = new Date(scheduledAt);
  if (Number.isNaN(when.getTime())) throw new BadRequestError('scheduledAt is not a date');

  await prisma.fixture.update({
    where: { id: fixtureId },
    data: { scheduledAt: when, ...(venue !== undefined ? { venue } : {}) },
  });
  if (fixture.matchId) {
    await prisma.match.update({
      where: { id: fixture.matchId },
      data: { scheduledAt: when, ...(venue !== undefined ? { venue } : {}) },
    });
  }
  return { fixtureId, matchId: fixture.matchId, scheduledAt: when.toISOString() };
}

// ─────────────────────────────────────────────────────────────────────────────
// A result arriving from the Match Centre
// ─────────────────────────────────────────────────────────────────────────────

export interface LeagueSyncOutcome {
  /** Null when this match is not a league match — the common case. */
  competitionId: string | null;
  fixtureId?: string;
  status?: string;
  standingsRebuilt?: number;
}

/**
 * Called whenever any Match in the platform changes state. Almost always a
 * no-op: only a match a league fixture points at is a league match, and that is
 * settled by a single indexed lookup rather than by inspecting the match.
 *
 * When it is one, the fixture takes the match's score and status and the table
 * is rebuilt by the engine that owns that arithmetic. Nothing is recomputed
 * here, and nobody enters the result twice.
 */
export async function syncMatchToLeague(matchId: string): Promise<LeagueSyncOutcome> {
  const fixture = await prisma.fixture.findFirst({
    where: { matchId },
    select: { id: true, competitionId: true, status: true },
  });
  if (!fixture) return { competitionId: null };

  const comp = await prisma.competition.findFirst({
    where: { id: fixture.competitionId, clubId: null },
    select: { id: true },
  });
  if (!comp) return { competitionId: null };

  const match = await prisma.match.findUnique({
    where: { id: matchId },
    select: { status: true, homeScore: true, awayScore: true, playedAt: true, scheduledAt: true },
  });
  if (!match) return { competitionId: null };

  // The Match's home and away are the fixture's home and away — the Match was
  // created from the fixture that way — so the scores map across directly and
  // no orientation has to be worked out.
  const settled = match.status === MatchStatus.FT;
  const called = match.status === MatchStatus.ABANDONED || match.status === MatchStatus.CANCELLED;
  const status = settled ? 'PLAYED' : called ? 'CANCELLED' : match.status === MatchStatus.POSTPONED ? 'POSTPONED' : 'SCHEDULED';

  await prisma.fixture.update({
    where: { id: fixture.id },
    data: {
      status,
      scheduledAt: match.scheduledAt,
      homeScore: settled ? match.homeScore ?? 0 : null,
      awayScore: settled ? match.awayScore ?? 0 : null,
      playedAt: settled ? match.playedAt ?? new Date() : null,
    },
  });

  const rebuilt = await rebuildStandingsUnchecked(fixture.competitionId);
  return { competitionId: fixture.competitionId, fixtureId: fixture.id, status, standingsRebuilt: rebuilt };
}
