-- Migration: add_phase_q_and_password_reset
-- Generated by: npx prisma migrate diff
--   --from-schema-datamodel prisma/schema.prisma
--   --to-schema-datamodel schema.prisma
--   --script
-- Date: 2025-05-25
--
-- Covers:
--   • PasswordResetToken table (password-reset feature)
--   • Phase Q tables: DataProviderSession, TransferTarget, PlayerMarketValue,
--     PlayerContractStatus, PlayerMatchStats, PlayerSeasonStats,
--     Competition, CompetitionTeam, Fixture, StandingsEntry
--   • Column additions: Match.season, EventOutbox (topic/retryCount/processedAt/
--     failedAt/errorLog + optionals + defaults), MatchEvent (xG/spatial fields),
--     ScoutingReport (scout fields), VideoAsset (defaults + status normalisation)
--   • Safe DROP INDEX IF EXISTS / DROP TYPE IF EXISTS guards for production
--     databases that were bootstrapped via prisma db push (root schema.prisma).
--
-- PRODUCTION NOTE:
--   If the database was created via "prisma db push" (not from migrations), run
--   ONCE before the first "prisma migrate deploy":
--
--     npx prisma migrate resolve --applied 00000000000000_baseline \
--       --schema=prisma/schema.prisma
--     npx prisma migrate resolve --applied 20250525000000_add_phase_q_and_password_reset \
--       --schema=prisma/schema.prisma
--
--   This marks both migrations as applied without re-executing the SQL.

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateEnum
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TYPE "DataProviderSource" AS ENUM ('MANUAL', 'STATSBOMB', 'OPTA', 'WYSCOUT', 'INSTAT', 'TRACAB', 'SECONDSPECTRUM', 'HUDL', 'INTERNAL');

-- ─────────────────────────────────────────────────────────────────────────────
-- DropIndex (guarded — index only exists when bootstrapped from prisma/schema.prisma)
-- ─────────────────────────────────────────────────────────────────────────────
DROP INDEX IF EXISTS "VideoAsset_shareToken_key";

-- ─────────────────────────────────────────────────────────────────────────────
-- AlterTable: Match — add nullable season column
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "season" TEXT;

-- ─────────────────────────────────────────────────────────────────────────────
-- AlterTable: EventOutbox — new columns + relax constraints + add defaults
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "EventOutbox"
  ADD COLUMN IF NOT EXISTS "errorLog"    TEXT,
  ADD COLUMN IF NOT EXISTS "failedAt"    TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "processedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "retryCount"  INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "topic"       TEXT;

ALTER TABLE "EventOutbox" ALTER COLUMN "clubId"         DROP NOT NULL;
ALTER TABLE "EventOutbox" ALTER COLUMN "seq"            SET DEFAULT 0;
ALTER TABLE "EventOutbox" ALTER COLUMN "kind"           SET DEFAULT '';
ALTER TABLE "EventOutbox" ALTER COLUMN "idempotencyKey" DROP NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- AlterTable: VideoAsset — normalise types, drop old schema artefacts, add status
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "VideoAsset" DROP COLUMN IF EXISTS "shareToken";

-- Restore NOT NULL + defaults (no-op on databases already created from root schema)
ALTER TABLE "VideoAsset" ALTER COLUMN "source" SET NOT NULL;
ALTER TABLE "VideoAsset" ALTER COLUMN "source" SET DEFAULT 'UPLOAD';
ALTER TABLE "VideoAsset" ALTER COLUMN "format" SET NOT NULL;
ALTER TABLE "VideoAsset" ALTER COLUMN "format" SET DEFAULT 'MP4';
ALTER TABLE "VideoAsset" ALTER COLUMN "url"    SET NOT NULL;
ALTER TABLE "VideoAsset" ALTER COLUMN "url"    SET DEFAULT '';

-- Replace typed-enum columns with TEXT equivalents (enum types are being dropped)
ALTER TABLE "VideoAsset" DROP COLUMN IF EXISTS "sourceKind";
ALTER TABLE "VideoAsset" ADD COLUMN IF NOT EXISTS "sourceKind" TEXT;

ALTER TABLE "VideoAsset" DROP COLUMN IF EXISTS "status";
ALTER TABLE "VideoAsset" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'UPLOADED';

ALTER TABLE "VideoAsset" ALTER COLUMN "durationSec" SET DATA TYPE DOUBLE PRECISION;

-- ─────────────────────────────────────────────────────────────────────────────
-- AlterTable: MatchEvent — Phase Q xG / spatial / data-provider fields
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "MatchEvent"
  ADD COLUMN IF NOT EXISTS "bodyPart"           TEXT,
  ADD COLUMN IF NOT EXISTS "clubId"             TEXT,
  ADD COLUMN IF NOT EXISTS "dataSource"         TEXT NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS "durationSec"        DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "endX"               DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "endY"               DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "externalId"         TEXT,
  ADD COLUMN IF NOT EXISTS "externalMatchId"    TEXT,
  ADD COLUMN IF NOT EXISTS "isKeyPass"          BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "isPressured"        BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "isProgressivePass"  BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "isUnderPressure"    BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "minute"             INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "minuteMs"           BIGINT,
  ADD COLUMN IF NOT EXISTS "outcome"            TEXT,
  ADD COLUMN IF NOT EXISTS "passHeight"         TEXT,
  ADD COLUMN IF NOT EXISTS "passTechnique"      TEXT,
  ADD COLUMN IF NOT EXISTS "periodIndex"        INTEGER,
  ADD COLUMN IF NOT EXISTS "playerId"           TEXT,
  ADD COLUMN IF NOT EXISTS "relatedPlayerId"    TEXT,
  ADD COLUMN IF NOT EXISTS "second"             INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "shotTechnique"      TEXT,
  ADD COLUMN IF NOT EXISTS "teamId"             TEXT,
  ADD COLUMN IF NOT EXISTS "videoTimestampSec"  DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "x"                  DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "xa"                 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "xg"                 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "xgot"               DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "y"                  DOUBLE PRECISION;

ALTER TABLE "MatchEvent" ALTER COLUMN "analysisId" DROP NOT NULL;
ALTER TABLE "MatchEvent" ALTER COLUMN "occurredAtMs" SET DEFAULT 0;

-- type column: Prisma diff does DROP/ADD to switch from enum to TEXT
ALTER TABLE "MatchEvent" DROP COLUMN IF EXISTS "type";
ALTER TABLE "MatchEvent" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT '';

-- ─────────────────────────────────────────────────────────────────────────────
-- AlterTable: ScoutingReport — Phase Q scout intelligence fields
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "ScoutingReport"
  ADD COLUMN IF NOT EXISTS "clubId"           TEXT,
  ADD COLUMN IF NOT EXISTS "compositeScore"   DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "mental"           DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "observedAt"       TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "overallGrade"     TEXT,
  ADD COLUMN IF NOT EXISTS "physical"         DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "playerId"         TEXT,
  ADD COLUMN IF NOT EXISTS "potential"        DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "recommendation"   TEXT,
  ADD COLUMN IF NOT EXISTS "scoutId"          TEXT,
  ADD COLUMN IF NOT EXISTS "strengthsNotes"   TEXT,
  ADD COLUMN IF NOT EXISTS "summaryNotes"     TEXT,
  ADD COLUMN IF NOT EXISTS "tactical"         DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "technical"        DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "weaknessesNotes"  TEXT;

ALTER TABLE "ScoutingReport" ALTER COLUMN "kind"    SET DEFAULT 'MATCH_REPORT';
ALTER TABLE "ScoutingReport" ALTER COLUMN "title"   SET DEFAULT '';
ALTER TABLE "ScoutingReport" ALTER COLUMN "summary" SET DEFAULT '';
ALTER TABLE "ScoutingReport" ALTER COLUMN "payload" SET DEFAULT '{}';

-- ─────────────────────────────────────────────────────────────────────────────
-- AlterTable: VideoTranscodeJob — normalise status to TEXT
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE "VideoTranscodeJob" DROP COLUMN IF EXISTS "profile";
ALTER TABLE "VideoTranscodeJob" DROP COLUMN IF EXISTS "status";
ALTER TABLE "VideoTranscodeJob" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'QUEUED';

-- ─────────────────────────────────────────────────────────────────────────────
-- DropEnum (guarded — only exist when bootstrapped from prisma/schema.prisma)
-- ─────────────────────────────────────────────────────────────────────────────
DROP TYPE IF EXISTS "VideoAssetStatus";
DROP TYPE IF EXISTS "VideoSourceKind";
DROP TYPE IF EXISTS "VideoTranscodeProfile";
DROP TYPE IF EXISTS "VideoTranscodeStatus";

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: PasswordResetToken
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "PasswordResetToken" (
    "id"        TEXT NOT NULL,
    "userId"    TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "usedAt"    TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PasswordResetToken_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: DataProviderSession
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "DataProviderSession" (
    "id"               TEXT NOT NULL,
    "clubId"           TEXT NOT NULL,
    "matchId"          TEXT,
    "source"           "DataProviderSource" NOT NULL DEFAULT 'MANUAL',
    "status"           TEXT NOT NULL DEFAULT 'RUNNING',
    "eventsIngested"   INTEGER NOT NULL DEFAULT 0,
    "eventsRejected"   INTEGER NOT NULL DEFAULT 0,
    "errorLog"         JSONB,
    "startedAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt"      TIMESTAMP(3),
    "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"        TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DataProviderSession_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: TransferTarget
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "TransferTarget" (
    "id"               TEXT NOT NULL,
    "clubId"           TEXT NOT NULL,
    "playerId"         TEXT NOT NULL,
    "stage"            TEXT NOT NULL DEFAULT 'LONGLIST',
    "position"         TEXT,
    "preferredFoot"    TEXT,
    "nationality"      TEXT,
    "currentClubName"  TEXT,
    "askingPriceMEur"  DOUBLE PRECISION,
    "budgetCapMEur"    DOUBLE PRECISION,
    "priorityScore"    INTEGER NOT NULL DEFAULT 50,
    "notes"            TEXT,
    "archivedAt"       TIMESTAMP(3),
    "createdBy"        TEXT,
    "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"        TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TransferTarget_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: PlayerMarketValue
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "PlayerMarketValue" (
    "id"            TEXT NOT NULL,
    "clubId"        TEXT NOT NULL,
    "playerId"      TEXT NOT NULL,
    "valuationDate" TIMESTAMP(3) NOT NULL,
    "valueMEur"     DOUBLE PRECISION NOT NULL,
    "source"        TEXT NOT NULL,
    "notes"         TEXT,
    "recordedBy"    TEXT,
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PlayerMarketValue_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: PlayerContractStatus
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "PlayerContractStatus" (
    "id"                     TEXT NOT NULL,
    "clubId"                 TEXT NOT NULL,
    "playerId"               TEXT NOT NULL,
    "contractExpiry"         TIMESTAMP(3) NOT NULL,
    "contractValueEur"       DOUBLE PRECISION,
    "releaseClauseEur"       DOUBLE PRECISION,
    "agentName"              TEXT,
    "agentContact"           TEXT,
    "expiryAlertDays"        INTEGER NOT NULL DEFAULT 180,
    "isExpiringSoon"         BOOLEAN NOT NULL DEFAULT false,
    "isAvailableForTransfer" BOOLEAN NOT NULL DEFAULT false,
    "notes"                  TEXT,
    "updatedBy"              TEXT,
    "createdAt"              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"              TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlayerContractStatus_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: PlayerMatchStats
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "PlayerMatchStats" (
    "id"                  TEXT NOT NULL,
    "matchId"             TEXT NOT NULL,
    "playerId"            TEXT NOT NULL,
    "clubId"              TEXT NOT NULL,
    "teamId"              TEXT,
    "minutesPlayed"       INTEGER NOT NULL DEFAULT 0,
    "isStarting"          BOOLEAN NOT NULL DEFAULT false,
    "goals"               INTEGER NOT NULL DEFAULT 0,
    "assists"             INTEGER NOT NULL DEFAULT 0,
    "shots"               INTEGER NOT NULL DEFAULT 0,
    "shotsOnTarget"       INTEGER NOT NULL DEFAULT 0,
    "shotsBlocked"        INTEGER NOT NULL DEFAULT 0,
    "xg"                  DOUBLE PRECISION NOT NULL DEFAULT 0,
    "xgot"                DOUBLE PRECISION NOT NULL DEFAULT 0,
    "xa"                  DOUBLE PRECISION NOT NULL DEFAULT 0,
    "keyPasses"           INTEGER NOT NULL DEFAULT 0,
    "bigChancesCreated"   INTEGER NOT NULL DEFAULT 0,
    "passes"              INTEGER NOT NULL DEFAULT 0,
    "passesCompleted"     INTEGER NOT NULL DEFAULT 0,
    "passAccuracy"        DOUBLE PRECISION NOT NULL DEFAULT 0,
    "progressivePasses"   INTEGER NOT NULL DEFAULT 0,
    "carries"             INTEGER NOT NULL DEFAULT 0,
    "progressiveCarries"  INTEGER NOT NULL DEFAULT 0,
    "dribbles"            INTEGER NOT NULL DEFAULT 0,
    "dribblesCompleted"   INTEGER NOT NULL DEFAULT 0,
    "pressures"           INTEGER NOT NULL DEFAULT 0,
    "pressuresSuccessful" INTEGER NOT NULL DEFAULT 0,
    "tackles"             INTEGER NOT NULL DEFAULT 0,
    "tacklesWon"          INTEGER NOT NULL DEFAULT 0,
    "interceptions"       INTEGER NOT NULL DEFAULT 0,
    "clearances"          INTEGER NOT NULL DEFAULT 0,
    "blockedShots"        INTEGER NOT NULL DEFAULT 0,
    "aerialDuels"         INTEGER NOT NULL DEFAULT 0,
    "aerialDuelsWon"      INTEGER NOT NULL DEFAULT 0,
    "groundDuels"         INTEGER NOT NULL DEFAULT 0,
    "groundDuelsWon"      INTEGER NOT NULL DEFAULT 0,
    "foulsCommitted"      INTEGER NOT NULL DEFAULT 0,
    "foulsSuffered"       INTEGER NOT NULL DEFAULT 0,
    "yellowCards"         INTEGER NOT NULL DEFAULT 0,
    "redCards"            INTEGER NOT NULL DEFAULT 0,
    "offsides"            INTEGER NOT NULL DEFAULT 0,
    "heatmapGrid"         JSONB,
    "ratingFamilista"     DOUBLE PRECISION,
    "computedAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt"           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"           TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlayerMatchStats_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: PlayerSeasonStats
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "PlayerSeasonStats" (
    "id"                   TEXT NOT NULL,
    "playerId"             TEXT NOT NULL,
    "clubId"               TEXT NOT NULL,
    "season"               TEXT NOT NULL,
    "competitionId"        TEXT,
    "appearances"          INTEGER NOT NULL DEFAULT 0,
    "starts"               INTEGER NOT NULL DEFAULT 0,
    "minutesPlayed"        INTEGER NOT NULL DEFAULT 0,
    "goals"                INTEGER NOT NULL DEFAULT 0,
    "assists"              INTEGER NOT NULL DEFAULT 0,
    "xg"                   DOUBLE PRECISION NOT NULL DEFAULT 0,
    "xa"                   DOUBLE PRECISION NOT NULL DEFAULT 0,
    "xgPer90"              DOUBLE PRECISION NOT NULL DEFAULT 0,
    "xaPer90"              DOUBLE PRECISION NOT NULL DEFAULT 0,
    "goalsPer90"           DOUBLE PRECISION NOT NULL DEFAULT 0,
    "assistsPer90"         DOUBLE PRECISION NOT NULL DEFAULT 0,
    "passAccuracy"         DOUBLE PRECISION NOT NULL DEFAULT 0,
    "pressureSuccessRate"  DOUBLE PRECISION NOT NULL DEFAULT 0,
    "aerialSuccessRate"    DOUBLE PRECISION NOT NULL DEFAULT 0,
    "dribbleSuccessRate"   DOUBLE PRECISION NOT NULL DEFAULT 0,
    "averageRating"        DOUBLE PRECISION NOT NULL DEFAULT 0,
    "avgDistancePer90"     DOUBLE PRECISION NOT NULL DEFAULT 0,
    "avgSprintsPer90"      DOUBLE PRECISION NOT NULL DEFAULT 0,
    "computedAt"           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"            TIMESTAMP(3) NOT NULL,
    "createdAt"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PlayerSeasonStats_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: Competition
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Competition" (
    "id"          TEXT NOT NULL,
    "clubId"      TEXT NOT NULL,
    "name"        TEXT NOT NULL,
    "code"        TEXT NOT NULL,
    "season"      TEXT NOT NULL,
    "format"      TEXT NOT NULL DEFAULT 'LEAGUE',
    "ageGroup"    TEXT,
    "gender"      TEXT,
    "countryCode" TEXT,
    "description" TEXT,
    "createdBy"   TEXT,
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"   TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Competition_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: CompetitionTeam
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "CompetitionTeam" (
    "id"            TEXT NOT NULL,
    "competitionId" TEXT NOT NULL,
    "teamId"        TEXT NOT NULL,
    "clubId"        TEXT NOT NULL,
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CompetitionTeam_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: Fixture
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Fixture" (
    "id"             TEXT NOT NULL,
    "competitionId"  TEXT NOT NULL,
    "clubId"         TEXT NOT NULL,
    "homeTeamId"     TEXT NOT NULL,
    "awayTeamId"     TEXT NOT NULL,
    "scheduledAt"    TIMESTAMP(3) NOT NULL,
    "venue"          TEXT,
    "round"          INTEGER,
    "leg"            INTEGER,
    "status"         TEXT NOT NULL DEFAULT 'SCHEDULED',
    "homeScore"      INTEGER,
    "awayScore"      INTEGER,
    "homeScoreAet"   INTEGER,
    "awayScoreAet"   INTEGER,
    "homePenalties"  INTEGER,
    "awayPenalties"  INTEGER,
    "playedAt"       TIMESTAMP(3),
    "matchId"        TEXT,
    "createdAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"      TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Fixture_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateTable: StandingsEntry
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "StandingsEntry" (
    "id"            TEXT NOT NULL,
    "competitionId" TEXT NOT NULL,
    "teamId"        TEXT NOT NULL,
    "position"      INTEGER NOT NULL,
    "played"        INTEGER NOT NULL DEFAULT 0,
    "won"           INTEGER NOT NULL DEFAULT 0,
    "drawn"         INTEGER NOT NULL DEFAULT 0,
    "lost"          INTEGER NOT NULL DEFAULT 0,
    "goalsFor"      INTEGER NOT NULL DEFAULT 0,
    "goalsAgainst"  INTEGER NOT NULL DEFAULT 0,
    "goalDiff"      INTEGER NOT NULL DEFAULT 0,
    "points"        INTEGER NOT NULL DEFAULT 0,
    "form"          TEXT NOT NULL DEFAULT '',
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"     TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StandingsEntry_pkey" PRIMARY KEY ("id")
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CreateIndex
-- ─────────────────────────────────────────────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS "PasswordResetToken_tokenHash_key"        ON "PasswordResetToken"("tokenHash");
CREATE INDEX        IF NOT EXISTS "PasswordResetToken_userId_idx"            ON "PasswordResetToken"("userId");
CREATE INDEX        IF NOT EXISTS "PasswordResetToken_expiresAt_idx"         ON "PasswordResetToken"("expiresAt");

CREATE INDEX        IF NOT EXISTS "DataProviderSession_clubId_matchId_idx"   ON "DataProviderSession"("clubId", "matchId");
CREATE INDEX        IF NOT EXISTS "DataProviderSession_status_idx"           ON "DataProviderSession"("status");

CREATE INDEX        IF NOT EXISTS "TransferTarget_clubId_stage_idx"          ON "TransferTarget"("clubId", "stage");
CREATE INDEX        IF NOT EXISTS "TransferTarget_clubId_archivedAt_idx"     ON "TransferTarget"("clubId", "archivedAt");
CREATE INDEX        IF NOT EXISTS "TransferTarget_playerId_idx"              ON "TransferTarget"("playerId");

CREATE INDEX        IF NOT EXISTS "PlayerMarketValue_clubId_playerId_valuationDate_idx"  ON "PlayerMarketValue"("clubId", "playerId", "valuationDate");
CREATE INDEX        IF NOT EXISTS "PlayerMarketValue_playerId_valuationDate_idx"         ON "PlayerMarketValue"("playerId", "valuationDate");

CREATE UNIQUE INDEX IF NOT EXISTS "PlayerContractStatus_playerId_key"        ON "PlayerContractStatus"("playerId");
CREATE INDEX        IF NOT EXISTS "PlayerContractStatus_clubId_idx"          ON "PlayerContractStatus"("clubId");
CREATE INDEX        IF NOT EXISTS "PlayerContractStatus_contractExpiry_idx"  ON "PlayerContractStatus"("contractExpiry");
CREATE INDEX        IF NOT EXISTS "PlayerContractStatus_isExpiringSoon_idx"  ON "PlayerContractStatus"("isExpiringSoon");

CREATE INDEX        IF NOT EXISTS "PlayerMatchStats_matchId_idx"             ON "PlayerMatchStats"("matchId");
CREATE INDEX        IF NOT EXISTS "PlayerMatchStats_playerId_idx"            ON "PlayerMatchStats"("playerId");
CREATE INDEX        IF NOT EXISTS "PlayerMatchStats_clubId_idx"              ON "PlayerMatchStats"("clubId");
CREATE UNIQUE INDEX IF NOT EXISTS "PlayerMatchStats_matchId_playerId_key"    ON "PlayerMatchStats"("matchId", "playerId");

CREATE INDEX        IF NOT EXISTS "PlayerSeasonStats_playerId_idx"           ON "PlayerSeasonStats"("playerId");
CREATE INDEX        IF NOT EXISTS "PlayerSeasonStats_clubId_season_idx"      ON "PlayerSeasonStats"("clubId", "season");
CREATE INDEX        IF NOT EXISTS "PlayerSeasonStats_competitionId_idx"      ON "PlayerSeasonStats"("competitionId");
CREATE UNIQUE INDEX IF NOT EXISTS "PlayerSeasonStats_playerId_clubId_season_competitionId_key" ON "PlayerSeasonStats"("playerId", "clubId", "season", "competitionId");

CREATE INDEX        IF NOT EXISTS "Competition_clubId_season_idx"            ON "Competition"("clubId", "season");
CREATE UNIQUE INDEX IF NOT EXISTS "Competition_clubId_code_season_key"       ON "Competition"("clubId", "code", "season");

CREATE INDEX        IF NOT EXISTS "CompetitionTeam_competitionId_idx"        ON "CompetitionTeam"("competitionId");
CREATE INDEX        IF NOT EXISTS "CompetitionTeam_teamId_idx"               ON "CompetitionTeam"("teamId");
CREATE UNIQUE INDEX IF NOT EXISTS "CompetitionTeam_competitionId_teamId_key" ON "CompetitionTeam"("competitionId", "teamId");

CREATE INDEX        IF NOT EXISTS "Fixture_competitionId_round_idx"          ON "Fixture"("competitionId", "round");
CREATE INDEX        IF NOT EXISTS "Fixture_clubId_idx"                       ON "Fixture"("clubId");
CREATE INDEX        IF NOT EXISTS "Fixture_homeTeamId_idx"                   ON "Fixture"("homeTeamId");
CREATE INDEX        IF NOT EXISTS "Fixture_awayTeamId_idx"                   ON "Fixture"("awayTeamId");
CREATE INDEX        IF NOT EXISTS "Fixture_matchId_idx"                      ON "Fixture"("matchId");
CREATE INDEX        IF NOT EXISTS "Fixture_status_idx"                       ON "Fixture"("status");

CREATE INDEX        IF NOT EXISTS "StandingsEntry_competitionId_position_idx" ON "StandingsEntry"("competitionId", "position");
CREATE UNIQUE INDEX IF NOT EXISTS "StandingsEntry_competitionId_teamId_key"   ON "StandingsEntry"("competitionId", "teamId");

CREATE INDEX        IF NOT EXISTS "EventOutbox_topic_processedAt_idx"        ON "EventOutbox"("topic", "processedAt");
CREATE INDEX        IF NOT EXISTS "VideoAsset_status_idx"                    ON "VideoAsset"("status");

CREATE UNIQUE INDEX IF NOT EXISTS "MatchEvent_externalId_key"                    ON "MatchEvent"("externalId");
CREATE INDEX        IF NOT EXISTS "MatchEvent_matchId_periodIndex_minuteMs_idx"  ON "MatchEvent"("matchId", "periodIndex", "minuteMs");
CREATE INDEX        IF NOT EXISTS "MatchEvent_playerId_idx"                      ON "MatchEvent"("playerId");
CREATE INDEX        IF NOT EXISTS "MatchEvent_externalId_idx"                    ON "MatchEvent"("externalId");
CREATE INDEX        IF NOT EXISTS "MatchEvent_clubId_idx"                        ON "MatchEvent"("clubId");

CREATE INDEX IF NOT EXISTS "ScoutingReport_clubId_playerId_idx"              ON "ScoutingReport"("clubId", "playerId");
CREATE INDEX IF NOT EXISTS "ScoutingReport_clubId_scoutId_idx"               ON "ScoutingReport"("clubId", "scoutId");

CREATE INDEX IF NOT EXISTS "VideoTranscodeJob_status_priority_queuedAt_idx"  ON "VideoTranscodeJob"("status", "priority", "queuedAt");

-- ─────────────────────────────────────────────────────────────────────────────
-- AddForeignKey
-- ─────────────────────────────────────────────────────────────────────────────
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'PasswordResetToken_userId_fkey'
  ) THEN
    ALTER TABLE "PasswordResetToken"
      ADD CONSTRAINT "PasswordResetToken_userId_fkey"
      FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'MatchEvent_matchId_fkey'
  ) THEN
    ALTER TABLE "MatchEvent"
      ADD CONSTRAINT "MatchEvent_matchId_fkey"
      FOREIGN KEY ("matchId") REFERENCES "Match"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'PlayerMarketValue_playerId_fkey'
  ) THEN
    ALTER TABLE "PlayerMarketValue"
      ADD CONSTRAINT "PlayerMarketValue_playerId_fkey"
      FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'PlayerContractStatus_playerId_fkey'
  ) THEN
    ALTER TABLE "PlayerContractStatus"
      ADD CONSTRAINT "PlayerContractStatus_playerId_fkey"
      FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'PlayerMatchStats_matchId_fkey'
  ) THEN
    ALTER TABLE "PlayerMatchStats"
      ADD CONSTRAINT "PlayerMatchStats_matchId_fkey"
      FOREIGN KEY ("matchId") REFERENCES "Match"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'PlayerMatchStats_playerId_fkey'
  ) THEN
    ALTER TABLE "PlayerMatchStats"
      ADD CONSTRAINT "PlayerMatchStats_playerId_fkey"
      FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'PlayerSeasonStats_playerId_fkey'
  ) THEN
    ALTER TABLE "PlayerSeasonStats"
      ADD CONSTRAINT "PlayerSeasonStats_playerId_fkey"
      FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'PlayerSeasonStats_competitionId_fkey'
  ) THEN
    ALTER TABLE "PlayerSeasonStats"
      ADD CONSTRAINT "PlayerSeasonStats_competitionId_fkey"
      FOREIGN KEY ("competitionId") REFERENCES "Competition"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'CompetitionTeam_competitionId_fkey'
  ) THEN
    ALTER TABLE "CompetitionTeam"
      ADD CONSTRAINT "CompetitionTeam_competitionId_fkey"
      FOREIGN KEY ("competitionId") REFERENCES "Competition"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'Fixture_competitionId_fkey'
  ) THEN
    ALTER TABLE "Fixture"
      ADD CONSTRAINT "Fixture_competitionId_fkey"
      FOREIGN KEY ("competitionId") REFERENCES "Competition"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'Fixture_matchId_fkey'
  ) THEN
    ALTER TABLE "Fixture"
      ADD CONSTRAINT "Fixture_matchId_fkey"
      FOREIGN KEY ("matchId") REFERENCES "Match"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
